// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: AccessPoint.proto

package acproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessPoint_AddressType int32

const (
	AccessPoint_kIPV4   AccessPoint_AddressType = 0
	AccessPoint_kIPV6   AccessPoint_AddressType = 1
	AccessPoint_kDomain AccessPoint_AddressType = 2
	AccessPoint_kQuic   AccessPoint_AddressType = 3
	AccessPoint_kQuicV6 AccessPoint_AddressType = 4
)

// Enum value maps for AccessPoint_AddressType.
var (
	AccessPoint_AddressType_name = map[int32]string{
		0: "kIPV4",
		1: "kIPV6",
		2: "kDomain",
		3: "kQuic",
		4: "kQuicV6",
	}
	AccessPoint_AddressType_value = map[string]int32{
		"kIPV4":   0,
		"kIPV6":   1,
		"kDomain": 2,
		"kQuic":   3,
		"kQuicV6": 4,
	}
)

func (x AccessPoint_AddressType) Enum() *AccessPoint_AddressType {
	p := new(AccessPoint_AddressType)
	*p = x
	return p
}

func (x AccessPoint_AddressType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessPoint_AddressType) Descriptor() protoreflect.EnumDescriptor {
	return file_AccessPoint_proto_enumTypes[0].Descriptor()
}

func (AccessPoint_AddressType) Type() protoreflect.EnumType {
	return &file_AccessPoint_proto_enumTypes[0]
}

func (x AccessPoint_AddressType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessPoint_AddressType.Descriptor instead.
func (AccessPoint_AddressType) EnumDescriptor() ([]byte, []int) {
	return file_AccessPoint_proto_rawDescGZIP(), []int{0, 0}
}

type AccessPoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AddressType AccessPoint_AddressType `protobuf:"varint,1,opt,name=addressType,proto3,enum=AcFunDanmu.Im.Basic.AccessPoint_AddressType" json:"addressType,omitempty"`
	Port        uint32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	IpV4        uint32                  `protobuf:"fixed32,3,opt,name=ipV4,proto3" json:"ipV4,omitempty"`
	IpV6        []byte                  `protobuf:"bytes,4,opt,name=ipV6,proto3" json:"ipV6,omitempty"`
	Domain      string                  `protobuf:"bytes,5,opt,name=domain,proto3" json:"domain,omitempty"`
	Quic        uint32                  `protobuf:"fixed32,6,opt,name=quic,proto3" json:"quic,omitempty"`
	QuicV6      []byte                  `protobuf:"bytes,7,opt,name=quicV6,proto3" json:"quicV6,omitempty"`
}

func (x *AccessPoint) Reset() {
	*x = AccessPoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AccessPoint_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessPoint) ProtoMessage() {}

func (x *AccessPoint) ProtoReflect() protoreflect.Message {
	mi := &file_AccessPoint_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessPoint.ProtoReflect.Descriptor instead.
func (*AccessPoint) Descriptor() ([]byte, []int) {
	return file_AccessPoint_proto_rawDescGZIP(), []int{0}
}

func (x *AccessPoint) GetAddressType() AccessPoint_AddressType {
	if x != nil {
		return x.AddressType
	}
	return AccessPoint_kIPV4
}

func (x *AccessPoint) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *AccessPoint) GetIpV4() uint32 {
	if x != nil {
		return x.IpV4
	}
	return 0
}

func (x *AccessPoint) GetIpV6() []byte {
	if x != nil {
		return x.IpV6
	}
	return nil
}

func (x *AccessPoint) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *AccessPoint) GetQuic() uint32 {
	if x != nil {
		return x.Quic
	}
	return 0
}

func (x *AccessPoint) GetQuicV6() []byte {
	if x != nil {
		return x.QuicV6
	}
	return nil
}

var File_AccessPoint_proto protoreflect.FileDescriptor

var file_AccessPoint_proto_rawDesc = []byte{
	0x0a, 0x11, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x13, 0x41, 0x63, 0x46, 0x75, 0x6e, 0x44, 0x61, 0x6e, 0x6d, 0x75, 0x2e,
	0x49, 0x6d, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x22, 0xa7, 0x02, 0x0a, 0x0b, 0x41, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x4e, 0x0a, 0x0b, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2c, 0x2e,
	0x41, 0x63, 0x46, 0x75, 0x6e, 0x44, 0x61, 0x6e, 0x6d, 0x75, 0x2e, 0x49, 0x6d, 0x2e, 0x42, 0x61,
	0x73, 0x69, 0x63, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x2e,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x69, 0x70, 0x56, 0x34, 0x18, 0x03, 0x20, 0x01, 0x28, 0x07, 0x52, 0x04, 0x69, 0x70, 0x56, 0x34,
	0x12, 0x12, 0x0a, 0x04, 0x69, 0x70, 0x56, 0x36, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x69, 0x70, 0x56, 0x36, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x71, 0x75, 0x69, 0x63, 0x18, 0x06, 0x20, 0x01, 0x28, 0x07, 0x52, 0x04, 0x71, 0x75, 0x69, 0x63,
	0x12, 0x16, 0x0a, 0x06, 0x71, 0x75, 0x69, 0x63, 0x56, 0x36, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x71, 0x75, 0x69, 0x63, 0x56, 0x36, 0x22, 0x48, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x6b, 0x49, 0x50, 0x56, 0x34,
	0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x6b, 0x49, 0x50, 0x56, 0x36, 0x10, 0x01, 0x12, 0x0b, 0x0a,
	0x07, 0x6b, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x6b, 0x51,
	0x75, 0x69, 0x63, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x6b, 0x51, 0x75, 0x69, 0x63, 0x56, 0x36,
	0x10, 0x04, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6f, 0x72, 0x7a, 0x6f, 0x67, 0x63, 0x2f, 0x61, 0x63, 0x66, 0x75, 0x6e, 0x64, 0x61, 0x6e,
	0x6d, 0x75, 0x2f, 0x61, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_AccessPoint_proto_rawDescOnce sync.Once
	file_AccessPoint_proto_rawDescData = file_AccessPoint_proto_rawDesc
)

func file_AccessPoint_proto_rawDescGZIP() []byte {
	file_AccessPoint_proto_rawDescOnce.Do(func() {
		file_AccessPoint_proto_rawDescData = protoimpl.X.CompressGZIP(file_AccessPoint_proto_rawDescData)
	})
	return file_AccessPoint_proto_rawDescData
}

var file_AccessPoint_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_AccessPoint_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_AccessPoint_proto_goTypes = []any{
	(AccessPoint_AddressType)(0), // 0: AcFunDanmu.Im.Basic.AccessPoint.AddressType
	(*AccessPoint)(nil),          // 1: AcFunDanmu.Im.Basic.AccessPoint
}
var file_AccessPoint_proto_depIdxs = []int32{
	0, // 0: AcFunDanmu.Im.Basic.AccessPoint.addressType:type_name -> AcFunDanmu.Im.Basic.AccessPoint.AddressType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_AccessPoint_proto_init() }
func file_AccessPoint_proto_init() {
	if File_AccessPoint_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_AccessPoint_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AccessPoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_AccessPoint_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_AccessPoint_proto_goTypes,
		DependencyIndexes: file_AccessPoint_proto_depIdxs,
		EnumInfos:         file_AccessPoint_proto_enumTypes,
		MessageInfos:      file_AccessPoint_proto_msgTypes,
	}.Build()
	File_AccessPoint_proto = out.File
	file_AccessPoint_proto_rawDesc = nil
	file_AccessPoint_proto_goTypes = nil
	file_AccessPoint_proto_depIdxs = nil
}
