// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: CommentNotice.proto

package acproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommentNotice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A string          `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	B []byte          `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
	C string          `protobuf:"bytes,3,opt,name=c,proto3" json:"c,omitempty"`
	D []*ImageCdnNode `protobuf:"bytes,4,rep,name=d,proto3" json:"d,omitempty"`
	E []*ImageCdnNode `protobuf:"bytes,5,rep,name=e,proto3" json:"e,omitempty"`
	F string          `protobuf:"bytes,6,opt,name=f,proto3" json:"f,omitempty"`
	G string          `protobuf:"bytes,7,opt,name=g,proto3" json:"g,omitempty"`
	H *Button         `protobuf:"bytes,8,opt,name=h,proto3" json:"h,omitempty"`
	I *ClickEvent     `protobuf:"bytes,9,opt,name=i,proto3" json:"i,omitempty"`
	J int32           `protobuf:"varint,10,opt,name=j,proto3" json:"j,omitempty"`
	K int64           `protobuf:"varint,11,opt,name=k,proto3" json:"k,omitempty"`
	L int64           `protobuf:"varint,12,opt,name=l,proto3" json:"l,omitempty"`
	M int32           `protobuf:"varint,13,opt,name=m,proto3" json:"m,omitempty"`
}

func (x *CommentNotice) Reset() {
	*x = CommentNotice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CommentNotice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommentNotice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentNotice) ProtoMessage() {}

func (x *CommentNotice) ProtoReflect() protoreflect.Message {
	mi := &file_CommentNotice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentNotice.ProtoReflect.Descriptor instead.
func (*CommentNotice) Descriptor() ([]byte, []int) {
	return file_CommentNotice_proto_rawDescGZIP(), []int{0}
}

func (x *CommentNotice) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

func (x *CommentNotice) GetB() []byte {
	if x != nil {
		return x.B
	}
	return nil
}

func (x *CommentNotice) GetC() string {
	if x != nil {
		return x.C
	}
	return ""
}

func (x *CommentNotice) GetD() []*ImageCdnNode {
	if x != nil {
		return x.D
	}
	return nil
}

func (x *CommentNotice) GetE() []*ImageCdnNode {
	if x != nil {
		return x.E
	}
	return nil
}

func (x *CommentNotice) GetF() string {
	if x != nil {
		return x.F
	}
	return ""
}

func (x *CommentNotice) GetG() string {
	if x != nil {
		return x.G
	}
	return ""
}

func (x *CommentNotice) GetH() *Button {
	if x != nil {
		return x.H
	}
	return nil
}

func (x *CommentNotice) GetI() *ClickEvent {
	if x != nil {
		return x.I
	}
	return nil
}

func (x *CommentNotice) GetJ() int32 {
	if x != nil {
		return x.J
	}
	return 0
}

func (x *CommentNotice) GetK() int64 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *CommentNotice) GetL() int64 {
	if x != nil {
		return x.L
	}
	return 0
}

func (x *CommentNotice) GetM() int32 {
	if x != nil {
		return x.M
	}
	return 0
}

var File_CommentNotice_proto protoreflect.FileDescriptor

var file_CommentNotice_proto_rawDesc = []byte{
	0x0a, 0x13, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x41, 0x63, 0x46, 0x75, 0x6e, 0x44, 0x61, 0x6e, 0x6d,
	0x75, 0x1a, 0x0c, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x10, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x12, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x43, 0x64, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa5, 0x02, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x01, 0x61, 0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x01, 0x62, 0x12, 0x0c, 0x0a, 0x01, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01,
	0x63, 0x12, 0x26, 0x0a, 0x01, 0x64, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x41,
	0x63, 0x46, 0x75, 0x6e, 0x44, 0x61, 0x6e, 0x6d, 0x75, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x43,
	0x64, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x01, 0x64, 0x12, 0x26, 0x0a, 0x01, 0x65, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x41, 0x63, 0x46, 0x75, 0x6e, 0x44, 0x61, 0x6e, 0x6d,
	0x75, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x43, 0x64, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x01,
	0x65, 0x12, 0x0c, 0x0a, 0x01, 0x66, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x66, 0x12,
	0x0c, 0x0a, 0x01, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x67, 0x12, 0x20, 0x0a,
	0x01, 0x68, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x41, 0x63, 0x46, 0x75, 0x6e,
	0x44, 0x61, 0x6e, 0x6d, 0x75, 0x2e, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x52, 0x01, 0x68, 0x12,
	0x24, 0x0a, 0x01, 0x69, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x41, 0x63, 0x46,
	0x75, 0x6e, 0x44, 0x61, 0x6e, 0x6d, 0x75, 0x2e, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x52, 0x01, 0x69, 0x12, 0x0c, 0x0a, 0x01, 0x6a, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x01, 0x6a, 0x12, 0x0c, 0x0a, 0x01, 0x6b, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01,
	0x6b, 0x12, 0x0c, 0x0a, 0x01, 0x6c, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x6c, 0x12,
	0x0c, 0x0a, 0x01, 0x6d, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x6d, 0x42, 0x26, 0x5a,
	0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x72, 0x7a, 0x6f,
	0x67, 0x63, 0x2f, 0x61, 0x63, 0x66, 0x75, 0x6e, 0x64, 0x61, 0x6e, 0x6d, 0x75, 0x2f, 0x61, 0x63,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_CommentNotice_proto_rawDescOnce sync.Once
	file_CommentNotice_proto_rawDescData = file_CommentNotice_proto_rawDesc
)

func file_CommentNotice_proto_rawDescGZIP() []byte {
	file_CommentNotice_proto_rawDescOnce.Do(func() {
		file_CommentNotice_proto_rawDescData = protoimpl.X.CompressGZIP(file_CommentNotice_proto_rawDescData)
	})
	return file_CommentNotice_proto_rawDescData
}

var file_CommentNotice_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CommentNotice_proto_goTypes = []any{
	(*CommentNotice)(nil), // 0: AcFunDanmu.CommentNotice
	(*ImageCdnNode)(nil),  // 1: AcFunDanmu.ImageCdnNode
	(*Button)(nil),        // 2: AcFunDanmu.Button
	(*ClickEvent)(nil),    // 3: AcFunDanmu.ClickEvent
}
var file_CommentNotice_proto_depIdxs = []int32{
	1, // 0: AcFunDanmu.CommentNotice.d:type_name -> AcFunDanmu.ImageCdnNode
	1, // 1: AcFunDanmu.CommentNotice.e:type_name -> AcFunDanmu.ImageCdnNode
	2, // 2: AcFunDanmu.CommentNotice.h:type_name -> AcFunDanmu.Button
	3, // 3: AcFunDanmu.CommentNotice.i:type_name -> AcFunDanmu.ClickEvent
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_CommentNotice_proto_init() }
func file_CommentNotice_proto_init() {
	if File_CommentNotice_proto != nil {
		return
	}
	file_Button_proto_init()
	file_ClickEvent_proto_init()
	file_ImageCdnNode_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_CommentNotice_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CommentNotice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_CommentNotice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CommentNotice_proto_goTypes,
		DependencyIndexes: file_CommentNotice_proto_depIdxs,
		MessageInfos:      file_CommentNotice_proto_msgTypes,
	}.Build()
	File_CommentNotice_proto = out.File
	file_CommentNotice_proto_rawDesc = nil
	file_CommentNotice_proto_goTypes = nil
	file_CommentNotice_proto_depIdxs = nil
}
