// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: CommonStateSignalAuthorChatCall.proto

package acproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommonStateSignalAuthorChatCall struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthorChatId    string                `protobuf:"bytes,1,opt,name=authorChatId,proto3" json:"authorChatId,omitempty"`
	InviterUserInfo *AuthorChatPlayerInfo `protobuf:"bytes,2,opt,name=inviterUserInfo,proto3" json:"inviterUserInfo,omitempty"`
	CallTimestampMs int64                 `protobuf:"varint,3,opt,name=callTimestampMs,proto3" json:"callTimestampMs,omitempty"`
}

func (x *CommonStateSignalAuthorChatCall) Reset() {
	*x = CommonStateSignalAuthorChatCall{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CommonStateSignalAuthorChatCall_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonStateSignalAuthorChatCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonStateSignalAuthorChatCall) ProtoMessage() {}

func (x *CommonStateSignalAuthorChatCall) ProtoReflect() protoreflect.Message {
	mi := &file_CommonStateSignalAuthorChatCall_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonStateSignalAuthorChatCall.ProtoReflect.Descriptor instead.
func (*CommonStateSignalAuthorChatCall) Descriptor() ([]byte, []int) {
	return file_CommonStateSignalAuthorChatCall_proto_rawDescGZIP(), []int{0}
}

func (x *CommonStateSignalAuthorChatCall) GetAuthorChatId() string {
	if x != nil {
		return x.AuthorChatId
	}
	return ""
}

func (x *CommonStateSignalAuthorChatCall) GetInviterUserInfo() *AuthorChatPlayerInfo {
	if x != nil {
		return x.InviterUserInfo
	}
	return nil
}

func (x *CommonStateSignalAuthorChatCall) GetCallTimestampMs() int64 {
	if x != nil {
		return x.CallTimestampMs
	}
	return 0
}

var File_CommonStateSignalAuthorChatCall_proto protoreflect.FileDescriptor

var file_CommonStateSignalAuthorChatCall_proto_rawDesc = []byte{
	0x0a, 0x25, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x53, 0x69, 0x67,
	0x6e, 0x61, 0x6c, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x43, 0x68, 0x61, 0x74, 0x43, 0x61, 0x6c,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x41, 0x63, 0x46, 0x75, 0x6e, 0x44, 0x61,
	0x6e, 0x6d, 0x75, 0x1a, 0x1a, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x43, 0x68, 0x61, 0x74, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xbb, 0x01, 0x0a, 0x1f, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x53,
	0x69, 0x67, 0x6e, 0x61, 0x6c, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x43, 0x68, 0x61, 0x74, 0x43,
	0x61, 0x6c, 0x6c, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x43, 0x68, 0x61,
	0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x43, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x4a, 0x0a, 0x0f, 0x69, 0x6e, 0x76, 0x69, 0x74,
	0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x41, 0x63, 0x46, 0x75, 0x6e, 0x44, 0x61, 0x6e, 0x6d, 0x75, 0x2e, 0x41, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x43, 0x68, 0x61, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x0f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x28, 0x0a, 0x0f, 0x63, 0x61, 0x6c, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x4d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x63, 0x61,
	0x6c, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x4d, 0x73, 0x42, 0x26, 0x5a,
	0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x72, 0x7a, 0x6f,
	0x67, 0x63, 0x2f, 0x61, 0x63, 0x66, 0x75, 0x6e, 0x64, 0x61, 0x6e, 0x6d, 0x75, 0x2f, 0x61, 0x63,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_CommonStateSignalAuthorChatCall_proto_rawDescOnce sync.Once
	file_CommonStateSignalAuthorChatCall_proto_rawDescData = file_CommonStateSignalAuthorChatCall_proto_rawDesc
)

func file_CommonStateSignalAuthorChatCall_proto_rawDescGZIP() []byte {
	file_CommonStateSignalAuthorChatCall_proto_rawDescOnce.Do(func() {
		file_CommonStateSignalAuthorChatCall_proto_rawDescData = protoimpl.X.CompressGZIP(file_CommonStateSignalAuthorChatCall_proto_rawDescData)
	})
	return file_CommonStateSignalAuthorChatCall_proto_rawDescData
}

var file_CommonStateSignalAuthorChatCall_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CommonStateSignalAuthorChatCall_proto_goTypes = []any{
	(*CommonStateSignalAuthorChatCall)(nil), // 0: AcFunDanmu.CommonStateSignalAuthorChatCall
	(*AuthorChatPlayerInfo)(nil),            // 1: AcFunDanmu.AuthorChatPlayerInfo
}
var file_CommonStateSignalAuthorChatCall_proto_depIdxs = []int32{
	1, // 0: AcFunDanmu.CommonStateSignalAuthorChatCall.inviterUserInfo:type_name -> AcFunDanmu.AuthorChatPlayerInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_CommonStateSignalAuthorChatCall_proto_init() }
func file_CommonStateSignalAuthorChatCall_proto_init() {
	if File_CommonStateSignalAuthorChatCall_proto != nil {
		return
	}
	file_AuthorChatPlayerInfo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_CommonStateSignalAuthorChatCall_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CommonStateSignalAuthorChatCall); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_CommonStateSignalAuthorChatCall_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CommonStateSignalAuthorChatCall_proto_goTypes,
		DependencyIndexes: file_CommonStateSignalAuthorChatCall_proto_depIdxs,
		MessageInfos:      file_CommonStateSignalAuthorChatCall_proto_msgTypes,
	}.Build()
	File_CommonStateSignalAuthorChatCall_proto = out.File
	file_CommonStateSignalAuthorChatCall_proto_rawDesc = nil
	file_CommonStateSignalAuthorChatCall_proto_goTypes = nil
	file_CommonStateSignalAuthorChatCall_proto_depIdxs = nil
}
