// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: CommonStateSignalAuthorResume.proto

package acproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommonStateSignalAuthorResume struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A int64 `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
}

func (x *CommonStateSignalAuthorResume) Reset() {
	*x = CommonStateSignalAuthorResume{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CommonStateSignalAuthorResume_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonStateSignalAuthorResume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonStateSignalAuthorResume) ProtoMessage() {}

func (x *CommonStateSignalAuthorResume) ProtoReflect() protoreflect.Message {
	mi := &file_CommonStateSignalAuthorResume_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonStateSignalAuthorResume.ProtoReflect.Descriptor instead.
func (*CommonStateSignalAuthorResume) Descriptor() ([]byte, []int) {
	return file_CommonStateSignalAuthorResume_proto_rawDescGZIP(), []int{0}
}

func (x *CommonStateSignalAuthorResume) GetA() int64 {
	if x != nil {
		return x.A
	}
	return 0
}

var File_CommonStateSignalAuthorResume_proto protoreflect.FileDescriptor

var file_CommonStateSignalAuthorResume_proto_rawDesc = []byte{
	0x0a, 0x23, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x53, 0x69, 0x67,
	0x6e, 0x61, 0x6c, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x41, 0x63, 0x46, 0x75, 0x6e, 0x44, 0x61, 0x6e, 0x6d,
	0x75, 0x22, 0x2d, 0x0a, 0x1d, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x75,
	0x6d, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x61,
	0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f,
	0x72, 0x7a, 0x6f, 0x67, 0x63, 0x2f, 0x61, 0x63, 0x66, 0x75, 0x6e, 0x64, 0x61, 0x6e, 0x6d, 0x75,
	0x2f, 0x61, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_CommonStateSignalAuthorResume_proto_rawDescOnce sync.Once
	file_CommonStateSignalAuthorResume_proto_rawDescData = file_CommonStateSignalAuthorResume_proto_rawDesc
)

func file_CommonStateSignalAuthorResume_proto_rawDescGZIP() []byte {
	file_CommonStateSignalAuthorResume_proto_rawDescOnce.Do(func() {
		file_CommonStateSignalAuthorResume_proto_rawDescData = protoimpl.X.CompressGZIP(file_CommonStateSignalAuthorResume_proto_rawDescData)
	})
	return file_CommonStateSignalAuthorResume_proto_rawDescData
}

var file_CommonStateSignalAuthorResume_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CommonStateSignalAuthorResume_proto_goTypes = []any{
	(*CommonStateSignalAuthorResume)(nil), // 0: AcFunDanmu.CommonStateSignalAuthorResume
}
var file_CommonStateSignalAuthorResume_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_CommonStateSignalAuthorResume_proto_init() }
func file_CommonStateSignalAuthorResume_proto_init() {
	if File_CommonStateSignalAuthorResume_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_CommonStateSignalAuthorResume_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CommonStateSignalAuthorResume); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_CommonStateSignalAuthorResume_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CommonStateSignalAuthorResume_proto_goTypes,
		DependencyIndexes: file_CommonStateSignalAuthorResume_proto_depIdxs,
		MessageInfos:      file_CommonStateSignalAuthorResume_proto_msgTypes,
	}.Build()
	File_CommonStateSignalAuthorResume_proto = out.File
	file_CommonStateSignalAuthorResume_proto_rawDesc = nil
	file_CommonStateSignalAuthorResume_proto_goTypes = nil
	file_CommonStateSignalAuthorResume_proto_depIdxs = nil
}
