// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.4
// source: CommonStateSignalAuthorChatChangeSoundConfig.proto

package acproto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CommonStateSignalAuthorChatChangesSoundConfig_Unknown int32

const (
	CommonStateSignalAuthorChatChangesSoundConfig_c CommonStateSignalAuthorChatChangesSoundConfig_Unknown = 0
	CommonStateSignalAuthorChatChangesSoundConfig_d CommonStateSignalAuthorChatChangesSoundConfig_Unknown = 1
	CommonStateSignalAuthorChatChangesSoundConfig_e CommonStateSignalAuthorChatChangesSoundConfig_Unknown = 2
)

// Enum value maps for CommonStateSignalAuthorChatChangesSoundConfig_Unknown.
var (
	CommonStateSignalAuthorChatChangesSoundConfig_Unknown_name = map[int32]string{
		0: "c",
		1: "d",
		2: "e",
	}
	CommonStateSignalAuthorChatChangesSoundConfig_Unknown_value = map[string]int32{
		"c": 0,
		"d": 1,
		"e": 2,
	}
)

func (x CommonStateSignalAuthorChatChangesSoundConfig_Unknown) Enum() *CommonStateSignalAuthorChatChangesSoundConfig_Unknown {
	p := new(CommonStateSignalAuthorChatChangesSoundConfig_Unknown)
	*p = x
	return p
}

func (x CommonStateSignalAuthorChatChangesSoundConfig_Unknown) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommonStateSignalAuthorChatChangesSoundConfig_Unknown) Descriptor() protoreflect.EnumDescriptor {
	return file_CommonStateSignalAuthorChatChangeSoundConfig_proto_enumTypes[0].Descriptor()
}

func (CommonStateSignalAuthorChatChangesSoundConfig_Unknown) Type() protoreflect.EnumType {
	return &file_CommonStateSignalAuthorChatChangeSoundConfig_proto_enumTypes[0]
}

func (x CommonStateSignalAuthorChatChangesSoundConfig_Unknown) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommonStateSignalAuthorChatChangesSoundConfig_Unknown.Descriptor instead.
func (CommonStateSignalAuthorChatChangesSoundConfig_Unknown) EnumDescriptor() ([]byte, []int) {
	return file_CommonStateSignalAuthorChatChangeSoundConfig_proto_rawDescGZIP(), []int{0, 0}
}

type CommonStateSignalAuthorChatChangesSoundConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A string                                                `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	B CommonStateSignalAuthorChatChangesSoundConfig_Unknown `protobuf:"varint,2,opt,name=b,proto3,enum=AcFunDanmu.CommonStateSignalAuthorChatChangesSoundConfig_Unknown" json:"b,omitempty"`
}

func (x *CommonStateSignalAuthorChatChangesSoundConfig) Reset() {
	*x = CommonStateSignalAuthorChatChangesSoundConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CommonStateSignalAuthorChatChangeSoundConfig_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonStateSignalAuthorChatChangesSoundConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonStateSignalAuthorChatChangesSoundConfig) ProtoMessage() {}

func (x *CommonStateSignalAuthorChatChangesSoundConfig) ProtoReflect() protoreflect.Message {
	mi := &file_CommonStateSignalAuthorChatChangeSoundConfig_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonStateSignalAuthorChatChangesSoundConfig.ProtoReflect.Descriptor instead.
func (*CommonStateSignalAuthorChatChangesSoundConfig) Descriptor() ([]byte, []int) {
	return file_CommonStateSignalAuthorChatChangeSoundConfig_proto_rawDescGZIP(), []int{0}
}

func (x *CommonStateSignalAuthorChatChangesSoundConfig) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

func (x *CommonStateSignalAuthorChatChangesSoundConfig) GetB() CommonStateSignalAuthorChatChangesSoundConfig_Unknown {
	if x != nil {
		return x.B
	}
	return CommonStateSignalAuthorChatChangesSoundConfig_c
}

var File_CommonStateSignalAuthorChatChangeSoundConfig_proto protoreflect.FileDescriptor

var file_CommonStateSignalAuthorChatChangeSoundConfig_proto_rawDesc = []byte{
	0x0a, 0x32, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x53, 0x69, 0x67,
	0x6e, 0x61, 0x6c, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x43, 0x68, 0x61, 0x74, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x53, 0x6f, 0x75, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x41, 0x63, 0x46, 0x75, 0x6e, 0x44, 0x61, 0x6e, 0x6d, 0x75,
	0x22, 0xae, 0x01, 0x0a, 0x2d, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x43, 0x68, 0x61, 0x74,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x53, 0x6f, 0x75, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x61,
	0x12, 0x4f, 0x0a, 0x01, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x41, 0x2e, 0x41, 0x63,
	0x46, 0x75, 0x6e, 0x44, 0x61, 0x6e, 0x6d, 0x75, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x43, 0x68, 0x61, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x53, 0x6f, 0x75, 0x6e, 0x64,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x52, 0x01,
	0x62, 0x22, 0x1e, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x12, 0x05, 0x0a, 0x01,
	0x63, 0x10, 0x00, 0x12, 0x05, 0x0a, 0x01, 0x64, 0x10, 0x01, 0x12, 0x05, 0x0a, 0x01, 0x65, 0x10,
	0x02, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x3b, 0x61, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_CommonStateSignalAuthorChatChangeSoundConfig_proto_rawDescOnce sync.Once
	file_CommonStateSignalAuthorChatChangeSoundConfig_proto_rawDescData = file_CommonStateSignalAuthorChatChangeSoundConfig_proto_rawDesc
)

func file_CommonStateSignalAuthorChatChangeSoundConfig_proto_rawDescGZIP() []byte {
	file_CommonStateSignalAuthorChatChangeSoundConfig_proto_rawDescOnce.Do(func() {
		file_CommonStateSignalAuthorChatChangeSoundConfig_proto_rawDescData = protoimpl.X.CompressGZIP(file_CommonStateSignalAuthorChatChangeSoundConfig_proto_rawDescData)
	})
	return file_CommonStateSignalAuthorChatChangeSoundConfig_proto_rawDescData
}

var file_CommonStateSignalAuthorChatChangeSoundConfig_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_CommonStateSignalAuthorChatChangeSoundConfig_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CommonStateSignalAuthorChatChangeSoundConfig_proto_goTypes = []interface{}{
	(CommonStateSignalAuthorChatChangesSoundConfig_Unknown)(0), // 0: AcFunDanmu.CommonStateSignalAuthorChatChangesSoundConfig.Unknown
	(*CommonStateSignalAuthorChatChangesSoundConfig)(nil),      // 1: AcFunDanmu.CommonStateSignalAuthorChatChangesSoundConfig
}
var file_CommonStateSignalAuthorChatChangeSoundConfig_proto_depIdxs = []int32{
	0, // 0: AcFunDanmu.CommonStateSignalAuthorChatChangesSoundConfig.b:type_name -> AcFunDanmu.CommonStateSignalAuthorChatChangesSoundConfig.Unknown
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_CommonStateSignalAuthorChatChangeSoundConfig_proto_init() }
func file_CommonStateSignalAuthorChatChangeSoundConfig_proto_init() {
	if File_CommonStateSignalAuthorChatChangeSoundConfig_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_CommonStateSignalAuthorChatChangeSoundConfig_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonStateSignalAuthorChatChangesSoundConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_CommonStateSignalAuthorChatChangeSoundConfig_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CommonStateSignalAuthorChatChangeSoundConfig_proto_goTypes,
		DependencyIndexes: file_CommonStateSignalAuthorChatChangeSoundConfig_proto_depIdxs,
		EnumInfos:         file_CommonStateSignalAuthorChatChangeSoundConfig_proto_enumTypes,
		MessageInfos:      file_CommonStateSignalAuthorChatChangeSoundConfig_proto_msgTypes,
	}.Build()
	File_CommonStateSignalAuthorChatChangeSoundConfig_proto = out.File
	file_CommonStateSignalAuthorChatChangeSoundConfig_proto_rawDesc = nil
	file_CommonStateSignalAuthorChatChangeSoundConfig_proto_goTypes = nil
	file_CommonStateSignalAuthorChatChangeSoundConfig_proto_depIdxs = nil
}
