// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.4
// source: CommonStateSignalAuthorChatEnd.proto

package acproto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CommonStateSignalAuthorChatEnd_Unknown int32

const (
	CommonStateSignalAuthorChatEnd_d CommonStateSignalAuthorChatEnd_Unknown = 0
	CommonStateSignalAuthorChatEnd_e CommonStateSignalAuthorChatEnd_Unknown = 1
	CommonStateSignalAuthorChatEnd_f CommonStateSignalAuthorChatEnd_Unknown = 2
	CommonStateSignalAuthorChatEnd_g CommonStateSignalAuthorChatEnd_Unknown = 3
	CommonStateSignalAuthorChatEnd_h CommonStateSignalAuthorChatEnd_Unknown = 4
	CommonStateSignalAuthorChatEnd_i CommonStateSignalAuthorChatEnd_Unknown = 5
	CommonStateSignalAuthorChatEnd_j CommonStateSignalAuthorChatEnd_Unknown = 6
	CommonStateSignalAuthorChatEnd_k CommonStateSignalAuthorChatEnd_Unknown = 7
	CommonStateSignalAuthorChatEnd_l CommonStateSignalAuthorChatEnd_Unknown = 8
)

// Enum value maps for CommonStateSignalAuthorChatEnd_Unknown.
var (
	CommonStateSignalAuthorChatEnd_Unknown_name = map[int32]string{
		0: "d",
		1: "e",
		2: "f",
		3: "g",
		4: "h",
		5: "i",
		6: "j",
		7: "k",
		8: "l",
	}
	CommonStateSignalAuthorChatEnd_Unknown_value = map[string]int32{
		"d": 0,
		"e": 1,
		"f": 2,
		"g": 3,
		"h": 4,
		"i": 5,
		"j": 6,
		"k": 7,
		"l": 8,
	}
)

func (x CommonStateSignalAuthorChatEnd_Unknown) Enum() *CommonStateSignalAuthorChatEnd_Unknown {
	p := new(CommonStateSignalAuthorChatEnd_Unknown)
	*p = x
	return p
}

func (x CommonStateSignalAuthorChatEnd_Unknown) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommonStateSignalAuthorChatEnd_Unknown) Descriptor() protoreflect.EnumDescriptor {
	return file_CommonStateSignalAuthorChatEnd_proto_enumTypes[0].Descriptor()
}

func (CommonStateSignalAuthorChatEnd_Unknown) Type() protoreflect.EnumType {
	return &file_CommonStateSignalAuthorChatEnd_proto_enumTypes[0]
}

func (x CommonStateSignalAuthorChatEnd_Unknown) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommonStateSignalAuthorChatEnd_Unknown.Descriptor instead.
func (CommonStateSignalAuthorChatEnd_Unknown) EnumDescriptor() ([]byte, []int) {
	return file_CommonStateSignalAuthorChatEnd_proto_rawDescGZIP(), []int{0, 0}
}

type CommonStateSignalAuthorChatEnd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A string                                 `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	B CommonStateSignalAuthorChatEnd_Unknown `protobuf:"varint,2,opt,name=b,proto3,enum=AcFunDanmu.CommonStateSignalAuthorChatEnd_Unknown" json:"b,omitempty"`
	C string                                 `protobuf:"bytes,3,opt,name=c,proto3" json:"c,omitempty"`
}

func (x *CommonStateSignalAuthorChatEnd) Reset() {
	*x = CommonStateSignalAuthorChatEnd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CommonStateSignalAuthorChatEnd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonStateSignalAuthorChatEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonStateSignalAuthorChatEnd) ProtoMessage() {}

func (x *CommonStateSignalAuthorChatEnd) ProtoReflect() protoreflect.Message {
	mi := &file_CommonStateSignalAuthorChatEnd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonStateSignalAuthorChatEnd.ProtoReflect.Descriptor instead.
func (*CommonStateSignalAuthorChatEnd) Descriptor() ([]byte, []int) {
	return file_CommonStateSignalAuthorChatEnd_proto_rawDescGZIP(), []int{0}
}

func (x *CommonStateSignalAuthorChatEnd) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

func (x *CommonStateSignalAuthorChatEnd) GetB() CommonStateSignalAuthorChatEnd_Unknown {
	if x != nil {
		return x.B
	}
	return CommonStateSignalAuthorChatEnd_d
}

func (x *CommonStateSignalAuthorChatEnd) GetC() string {
	if x != nil {
		return x.C
	}
	return ""
}

var File_CommonStateSignalAuthorChatEnd_proto protoreflect.FileDescriptor

var file_CommonStateSignalAuthorChatEnd_proto_rawDesc = []byte{
	0x0a, 0x24, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x53, 0x69, 0x67,
	0x6e, 0x61, 0x6c, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x43, 0x68, 0x61, 0x74, 0x45, 0x6e, 0x64,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x41, 0x63, 0x46, 0x75, 0x6e, 0x44, 0x61, 0x6e,
	0x6d, 0x75, 0x22, 0xc8, 0x01, 0x0a, 0x1e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x43, 0x68,
	0x61, 0x74, 0x45, 0x6e, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x01, 0x61, 0x12, 0x40, 0x0a, 0x01, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x32,
	0x2e, 0x41, 0x63, 0x46, 0x75, 0x6e, 0x44, 0x61, 0x6e, 0x6d, 0x75, 0x2e, 0x43, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x41, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x43, 0x68, 0x61, 0x74, 0x45, 0x6e, 0x64, 0x2e, 0x55, 0x6e, 0x6b, 0x6e, 0x6f,
	0x77, 0x6e, 0x52, 0x01, 0x62, 0x12, 0x0c, 0x0a, 0x01, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x01, 0x63, 0x22, 0x48, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x12, 0x05,
	0x0a, 0x01, 0x64, 0x10, 0x00, 0x12, 0x05, 0x0a, 0x01, 0x65, 0x10, 0x01, 0x12, 0x05, 0x0a, 0x01,
	0x66, 0x10, 0x02, 0x12, 0x05, 0x0a, 0x01, 0x67, 0x10, 0x03, 0x12, 0x05, 0x0a, 0x01, 0x68, 0x10,
	0x04, 0x12, 0x05, 0x0a, 0x01, 0x69, 0x10, 0x05, 0x12, 0x05, 0x0a, 0x01, 0x6a, 0x10, 0x06, 0x12,
	0x05, 0x0a, 0x01, 0x6b, 0x10, 0x07, 0x12, 0x05, 0x0a, 0x01, 0x6c, 0x10, 0x08, 0x42, 0x0b, 0x5a,
	0x09, 0x2e, 0x3b, 0x61, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_CommonStateSignalAuthorChatEnd_proto_rawDescOnce sync.Once
	file_CommonStateSignalAuthorChatEnd_proto_rawDescData = file_CommonStateSignalAuthorChatEnd_proto_rawDesc
)

func file_CommonStateSignalAuthorChatEnd_proto_rawDescGZIP() []byte {
	file_CommonStateSignalAuthorChatEnd_proto_rawDescOnce.Do(func() {
		file_CommonStateSignalAuthorChatEnd_proto_rawDescData = protoimpl.X.CompressGZIP(file_CommonStateSignalAuthorChatEnd_proto_rawDescData)
	})
	return file_CommonStateSignalAuthorChatEnd_proto_rawDescData
}

var file_CommonStateSignalAuthorChatEnd_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_CommonStateSignalAuthorChatEnd_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CommonStateSignalAuthorChatEnd_proto_goTypes = []interface{}{
	(CommonStateSignalAuthorChatEnd_Unknown)(0), // 0: AcFunDanmu.CommonStateSignalAuthorChatEnd.Unknown
	(*CommonStateSignalAuthorChatEnd)(nil),      // 1: AcFunDanmu.CommonStateSignalAuthorChatEnd
}
var file_CommonStateSignalAuthorChatEnd_proto_depIdxs = []int32{
	0, // 0: AcFunDanmu.CommonStateSignalAuthorChatEnd.b:type_name -> AcFunDanmu.CommonStateSignalAuthorChatEnd.Unknown
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_CommonStateSignalAuthorChatEnd_proto_init() }
func file_CommonStateSignalAuthorChatEnd_proto_init() {
	if File_CommonStateSignalAuthorChatEnd_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_CommonStateSignalAuthorChatEnd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonStateSignalAuthorChatEnd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_CommonStateSignalAuthorChatEnd_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CommonStateSignalAuthorChatEnd_proto_goTypes,
		DependencyIndexes: file_CommonStateSignalAuthorChatEnd_proto_depIdxs,
		EnumInfos:         file_CommonStateSignalAuthorChatEnd_proto_enumTypes,
		MessageInfos:      file_CommonStateSignalAuthorChatEnd_proto_msgTypes,
	}.Build()
	File_CommonStateSignalAuthorChatEnd_proto = out.File
	file_CommonStateSignalAuthorChatEnd_proto_rawDesc = nil
	file_CommonStateSignalAuthorChatEnd_proto_goTypes = nil
	file_CommonStateSignalAuthorChatEnd_proto_depIdxs = nil
}
