// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: CommonNotifySignalLiveManagerState.proto

package acproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommonNotifySignalLiveManagerState_ManagerState int32

const (
	CommonNotifySignalLiveManagerState_MANAGER_STATE_UNKNOWN CommonNotifySignalLiveManagerState_ManagerState = 0
	CommonNotifySignalLiveManagerState_MANAGER_ADDED         CommonNotifySignalLiveManagerState_ManagerState = 1
	CommonNotifySignalLiveManagerState_MANAGER_REMOVED       CommonNotifySignalLiveManagerState_ManagerState = 2
	CommonNotifySignalLiveManagerState_IS_MANAGER            CommonNotifySignalLiveManagerState_ManagerState = 3
)

// Enum value maps for CommonNotifySignalLiveManagerState_ManagerState.
var (
	CommonNotifySignalLiveManagerState_ManagerState_name = map[int32]string{
		0: "MANAGER_STATE_UNKNOWN",
		1: "MANAGER_ADDED",
		2: "MANAGER_REMOVED",
		3: "IS_MANAGER",
	}
	CommonNotifySignalLiveManagerState_ManagerState_value = map[string]int32{
		"MANAGER_STATE_UNKNOWN": 0,
		"MANAGER_ADDED":         1,
		"MANAGER_REMOVED":       2,
		"IS_MANAGER":            3,
	}
)

func (x CommonNotifySignalLiveManagerState_ManagerState) Enum() *CommonNotifySignalLiveManagerState_ManagerState {
	p := new(CommonNotifySignalLiveManagerState_ManagerState)
	*p = x
	return p
}

func (x CommonNotifySignalLiveManagerState_ManagerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommonNotifySignalLiveManagerState_ManagerState) Descriptor() protoreflect.EnumDescriptor {
	return file_CommonNotifySignalLiveManagerState_proto_enumTypes[0].Descriptor()
}

func (CommonNotifySignalLiveManagerState_ManagerState) Type() protoreflect.EnumType {
	return &file_CommonNotifySignalLiveManagerState_proto_enumTypes[0]
}

func (x CommonNotifySignalLiveManagerState_ManagerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommonNotifySignalLiveManagerState_ManagerState.Descriptor instead.
func (CommonNotifySignalLiveManagerState_ManagerState) EnumDescriptor() ([]byte, []int) {
	return file_CommonNotifySignalLiveManagerState_proto_rawDescGZIP(), []int{0, 0}
}

type CommonNotifySignalLiveManagerState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State CommonNotifySignalLiveManagerState_ManagerState `protobuf:"varint,1,opt,name=state,proto3,enum=AcFunDanmu.CommonNotifySignalLiveManagerState_ManagerState" json:"state,omitempty"`
}

func (x *CommonNotifySignalLiveManagerState) Reset() {
	*x = CommonNotifySignalLiveManagerState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CommonNotifySignalLiveManagerState_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonNotifySignalLiveManagerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonNotifySignalLiveManagerState) ProtoMessage() {}

func (x *CommonNotifySignalLiveManagerState) ProtoReflect() protoreflect.Message {
	mi := &file_CommonNotifySignalLiveManagerState_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonNotifySignalLiveManagerState.ProtoReflect.Descriptor instead.
func (*CommonNotifySignalLiveManagerState) Descriptor() ([]byte, []int) {
	return file_CommonNotifySignalLiveManagerState_proto_rawDescGZIP(), []int{0}
}

func (x *CommonNotifySignalLiveManagerState) GetState() CommonNotifySignalLiveManagerState_ManagerState {
	if x != nil {
		return x.State
	}
	return CommonNotifySignalLiveManagerState_MANAGER_STATE_UNKNOWN
}

var File_CommonNotifySignalLiveManagerState_proto protoreflect.FileDescriptor

var file_CommonNotifySignalLiveManagerState_proto_rawDesc = []byte{
	0x0a, 0x28, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x6c, 0x4c, 0x69, 0x76, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x41, 0x63, 0x46, 0x75,
	0x6e, 0x44, 0x61, 0x6e, 0x6d, 0x75, 0x22, 0xda, 0x01, 0x0a, 0x22, 0x43, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x4c, 0x69, 0x76,
	0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x51, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x3b, 0x2e, 0x41,
	0x63, 0x46, 0x75, 0x6e, 0x44, 0x61, 0x6e, 0x6d, 0x75, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x4c, 0x69, 0x76, 0x65,
	0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x4d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x22, 0x61, 0x0a, 0x0c, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x19, 0x0a, 0x15, 0x4d, 0x41, 0x4e, 0x41, 0x47, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x4d,
	0x41, 0x4e, 0x41, 0x47, 0x45, 0x52, 0x5f, 0x41, 0x44, 0x44, 0x45, 0x44, 0x10, 0x01, 0x12, 0x13,
	0x0a, 0x0f, 0x4d, 0x41, 0x4e, 0x41, 0x47, 0x45, 0x52, 0x5f, 0x52, 0x45, 0x4d, 0x4f, 0x56, 0x45,
	0x44, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x49, 0x53, 0x5f, 0x4d, 0x41, 0x4e, 0x41, 0x47, 0x45,
	0x52, 0x10, 0x03, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6f, 0x72, 0x7a, 0x6f, 0x67, 0x63, 0x2f, 0x61, 0x63, 0x66, 0x75, 0x6e, 0x64, 0x61,
	0x6e, 0x6d, 0x75, 0x2f, 0x61, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_CommonNotifySignalLiveManagerState_proto_rawDescOnce sync.Once
	file_CommonNotifySignalLiveManagerState_proto_rawDescData = file_CommonNotifySignalLiveManagerState_proto_rawDesc
)

func file_CommonNotifySignalLiveManagerState_proto_rawDescGZIP() []byte {
	file_CommonNotifySignalLiveManagerState_proto_rawDescOnce.Do(func() {
		file_CommonNotifySignalLiveManagerState_proto_rawDescData = protoimpl.X.CompressGZIP(file_CommonNotifySignalLiveManagerState_proto_rawDescData)
	})
	return file_CommonNotifySignalLiveManagerState_proto_rawDescData
}

var file_CommonNotifySignalLiveManagerState_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_CommonNotifySignalLiveManagerState_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CommonNotifySignalLiveManagerState_proto_goTypes = []any{
	(CommonNotifySignalLiveManagerState_ManagerState)(0), // 0: AcFunDanmu.CommonNotifySignalLiveManagerState.ManagerState
	(*CommonNotifySignalLiveManagerState)(nil),           // 1: AcFunDanmu.CommonNotifySignalLiveManagerState
}
var file_CommonNotifySignalLiveManagerState_proto_depIdxs = []int32{
	0, // 0: AcFunDanmu.CommonNotifySignalLiveManagerState.state:type_name -> AcFunDanmu.CommonNotifySignalLiveManagerState.ManagerState
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_CommonNotifySignalLiveManagerState_proto_init() }
func file_CommonNotifySignalLiveManagerState_proto_init() {
	if File_CommonNotifySignalLiveManagerState_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_CommonNotifySignalLiveManagerState_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CommonNotifySignalLiveManagerState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_CommonNotifySignalLiveManagerState_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CommonNotifySignalLiveManagerState_proto_goTypes,
		DependencyIndexes: file_CommonNotifySignalLiveManagerState_proto_depIdxs,
		EnumInfos:         file_CommonNotifySignalLiveManagerState_proto_enumTypes,
		MessageInfos:      file_CommonNotifySignalLiveManagerState_proto_msgTypes,
	}.Build()
	File_CommonNotifySignalLiveManagerState_proto = out.File
	file_CommonNotifySignalLiveManagerState_proto_rawDesc = nil
	file_CommonNotifySignalLiveManagerState_proto_goTypes = nil
	file_CommonNotifySignalLiveManagerState_proto_depIdxs = nil
}
