// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: CommonStateSignalAuthorChatChangeSoundConfig.proto

package acproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommonStateSignalAuthorChatChangeSoundConfig_SoundConfigChangeType int32

const (
	CommonStateSignalAuthorChatChangeSoundConfig_UNKNOWN     CommonStateSignalAuthorChatChangeSoundConfig_SoundConfigChangeType = 0
	CommonStateSignalAuthorChatChangeSoundConfig_OPEN_SOUND  CommonStateSignalAuthorChatChangeSoundConfig_SoundConfigChangeType = 1
	CommonStateSignalAuthorChatChangeSoundConfig_CLOSE_SOUND CommonStateSignalAuthorChatChangeSoundConfig_SoundConfigChangeType = 2
)

// Enum value maps for CommonStateSignalAuthorChatChangeSoundConfig_SoundConfigChangeType.
var (
	CommonStateSignalAuthorChatChangeSoundConfig_SoundConfigChangeType_name = map[int32]string{
		0: "UNKNOWN",
		1: "OPEN_SOUND",
		2: "CLOSE_SOUND",
	}
	CommonStateSignalAuthorChatChangeSoundConfig_SoundConfigChangeType_value = map[string]int32{
		"UNKNOWN":     0,
		"OPEN_SOUND":  1,
		"CLOSE_SOUND": 2,
	}
)

func (x CommonStateSignalAuthorChatChangeSoundConfig_SoundConfigChangeType) Enum() *CommonStateSignalAuthorChatChangeSoundConfig_SoundConfigChangeType {
	p := new(CommonStateSignalAuthorChatChangeSoundConfig_SoundConfigChangeType)
	*p = x
	return p
}

func (x CommonStateSignalAuthorChatChangeSoundConfig_SoundConfigChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommonStateSignalAuthorChatChangeSoundConfig_SoundConfigChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_CommonStateSignalAuthorChatChangeSoundConfig_proto_enumTypes[0].Descriptor()
}

func (CommonStateSignalAuthorChatChangeSoundConfig_SoundConfigChangeType) Type() protoreflect.EnumType {
	return &file_CommonStateSignalAuthorChatChangeSoundConfig_proto_enumTypes[0]
}

func (x CommonStateSignalAuthorChatChangeSoundConfig_SoundConfigChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommonStateSignalAuthorChatChangeSoundConfig_SoundConfigChangeType.Descriptor instead.
func (CommonStateSignalAuthorChatChangeSoundConfig_SoundConfigChangeType) EnumDescriptor() ([]byte, []int) {
	return file_CommonStateSignalAuthorChatChangeSoundConfig_proto_rawDescGZIP(), []int{0, 0}
}

type CommonStateSignalAuthorChatChangeSoundConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthorChatId          string                                                             `protobuf:"bytes,1,opt,name=authorChatId,proto3" json:"authorChatId,omitempty"`
	SoundConfigChangeType CommonStateSignalAuthorChatChangeSoundConfig_SoundConfigChangeType `protobuf:"varint,2,opt,name=soundConfigChangeType,proto3,enum=AcFunDanmu.CommonStateSignalAuthorChatChangeSoundConfig_SoundConfigChangeType" json:"soundConfigChangeType,omitempty"` // authorChatVoiceType
}

func (x *CommonStateSignalAuthorChatChangeSoundConfig) Reset() {
	*x = CommonStateSignalAuthorChatChangeSoundConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CommonStateSignalAuthorChatChangeSoundConfig_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonStateSignalAuthorChatChangeSoundConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonStateSignalAuthorChatChangeSoundConfig) ProtoMessage() {}

func (x *CommonStateSignalAuthorChatChangeSoundConfig) ProtoReflect() protoreflect.Message {
	mi := &file_CommonStateSignalAuthorChatChangeSoundConfig_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonStateSignalAuthorChatChangeSoundConfig.ProtoReflect.Descriptor instead.
func (*CommonStateSignalAuthorChatChangeSoundConfig) Descriptor() ([]byte, []int) {
	return file_CommonStateSignalAuthorChatChangeSoundConfig_proto_rawDescGZIP(), []int{0}
}

func (x *CommonStateSignalAuthorChatChangeSoundConfig) GetAuthorChatId() string {
	if x != nil {
		return x.AuthorChatId
	}
	return ""
}

func (x *CommonStateSignalAuthorChatChangeSoundConfig) GetSoundConfigChangeType() CommonStateSignalAuthorChatChangeSoundConfig_SoundConfigChangeType {
	if x != nil {
		return x.SoundConfigChangeType
	}
	return CommonStateSignalAuthorChatChangeSoundConfig_UNKNOWN
}

var File_CommonStateSignalAuthorChatChangeSoundConfig_proto protoreflect.FileDescriptor

var file_CommonStateSignalAuthorChatChangeSoundConfig_proto_rawDesc = []byte{
	0x0a, 0x32, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x53, 0x69, 0x67,
	0x6e, 0x61, 0x6c, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x43, 0x68, 0x61, 0x74, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x53, 0x6f, 0x75, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x41, 0x63, 0x46, 0x75, 0x6e, 0x44, 0x61, 0x6e, 0x6d, 0x75,
	0x22, 0xa0, 0x02, 0x0a, 0x2c, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x43, 0x68, 0x61, 0x74,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x6f, 0x75, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x43, 0x68, 0x61, 0x74, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x43,
	0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x84, 0x01, 0x0a, 0x15, 0x73, 0x6f, 0x75, 0x6e, 0x64, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x4e, 0x2e, 0x41, 0x63, 0x46, 0x75, 0x6e, 0x44, 0x61, 0x6e,
	0x6d, 0x75, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x6c, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x43, 0x68, 0x61, 0x74, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x53, 0x6f, 0x75, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e,
	0x53, 0x6f, 0x75, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x15, 0x73, 0x6f, 0x75, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x45, 0x0a, 0x15,
	0x53, 0x6f, 0x75, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e,
	0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x4f, 0x50, 0x45, 0x4e, 0x5f, 0x53, 0x4f, 0x55, 0x4e, 0x44,
	0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x5f, 0x53, 0x4f, 0x55, 0x4e,
	0x44, 0x10, 0x02, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6f, 0x72, 0x7a, 0x6f, 0x67, 0x63, 0x2f, 0x61, 0x63, 0x66, 0x75, 0x6e, 0x64, 0x61,
	0x6e, 0x6d, 0x75, 0x2f, 0x61, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_CommonStateSignalAuthorChatChangeSoundConfig_proto_rawDescOnce sync.Once
	file_CommonStateSignalAuthorChatChangeSoundConfig_proto_rawDescData = file_CommonStateSignalAuthorChatChangeSoundConfig_proto_rawDesc
)

func file_CommonStateSignalAuthorChatChangeSoundConfig_proto_rawDescGZIP() []byte {
	file_CommonStateSignalAuthorChatChangeSoundConfig_proto_rawDescOnce.Do(func() {
		file_CommonStateSignalAuthorChatChangeSoundConfig_proto_rawDescData = protoimpl.X.CompressGZIP(file_CommonStateSignalAuthorChatChangeSoundConfig_proto_rawDescData)
	})
	return file_CommonStateSignalAuthorChatChangeSoundConfig_proto_rawDescData
}

var file_CommonStateSignalAuthorChatChangeSoundConfig_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_CommonStateSignalAuthorChatChangeSoundConfig_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CommonStateSignalAuthorChatChangeSoundConfig_proto_goTypes = []any{
	(CommonStateSignalAuthorChatChangeSoundConfig_SoundConfigChangeType)(0), // 0: AcFunDanmu.CommonStateSignalAuthorChatChangeSoundConfig.SoundConfigChangeType
	(*CommonStateSignalAuthorChatChangeSoundConfig)(nil),                    // 1: AcFunDanmu.CommonStateSignalAuthorChatChangeSoundConfig
}
var file_CommonStateSignalAuthorChatChangeSoundConfig_proto_depIdxs = []int32{
	0, // 0: AcFunDanmu.CommonStateSignalAuthorChatChangeSoundConfig.soundConfigChangeType:type_name -> AcFunDanmu.CommonStateSignalAuthorChatChangeSoundConfig.SoundConfigChangeType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_CommonStateSignalAuthorChatChangeSoundConfig_proto_init() }
func file_CommonStateSignalAuthorChatChangeSoundConfig_proto_init() {
	if File_CommonStateSignalAuthorChatChangeSoundConfig_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_CommonStateSignalAuthorChatChangeSoundConfig_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CommonStateSignalAuthorChatChangeSoundConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_CommonStateSignalAuthorChatChangeSoundConfig_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CommonStateSignalAuthorChatChangeSoundConfig_proto_goTypes,
		DependencyIndexes: file_CommonStateSignalAuthorChatChangeSoundConfig_proto_depIdxs,
		EnumInfos:         file_CommonStateSignalAuthorChatChangeSoundConfig_proto_enumTypes,
		MessageInfos:      file_CommonStateSignalAuthorChatChangeSoundConfig_proto_msgTypes,
	}.Build()
	File_CommonStateSignalAuthorChatChangeSoundConfig_proto = out.File
	file_CommonStateSignalAuthorChatChangeSoundConfig_proto_rawDesc = nil
	file_CommonStateSignalAuthorChatChangeSoundConfig_proto_goTypes = nil
	file_CommonStateSignalAuthorChatChangeSoundConfig_proto_depIdxs = nil
}
