// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: CommonStateSignalChatCall.proto

package acproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommonStateSignalChatCall struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId          string        `protobuf:"bytes,1,opt,name=chatId,proto3" json:"chatId,omitempty"`
	LiveId          string        `protobuf:"bytes,2,opt,name=liveId,proto3" json:"liveId,omitempty"`
	CallTimestampMs int64         `protobuf:"varint,3,opt,name=callTimestampMs,proto3" json:"callTimestampMs,omitempty"`
	MediaType       ChatMediaType `protobuf:"varint,4,opt,name=mediaType,proto3,enum=AcFunDanmu.ChatMediaType" json:"mediaType,omitempty"`
}

func (x *CommonStateSignalChatCall) Reset() {
	*x = CommonStateSignalChatCall{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CommonStateSignalChatCall_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonStateSignalChatCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonStateSignalChatCall) ProtoMessage() {}

func (x *CommonStateSignalChatCall) ProtoReflect() protoreflect.Message {
	mi := &file_CommonStateSignalChatCall_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonStateSignalChatCall.ProtoReflect.Descriptor instead.
func (*CommonStateSignalChatCall) Descriptor() ([]byte, []int) {
	return file_CommonStateSignalChatCall_proto_rawDescGZIP(), []int{0}
}

func (x *CommonStateSignalChatCall) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *CommonStateSignalChatCall) GetLiveId() string {
	if x != nil {
		return x.LiveId
	}
	return ""
}

func (x *CommonStateSignalChatCall) GetCallTimestampMs() int64 {
	if x != nil {
		return x.CallTimestampMs
	}
	return 0
}

func (x *CommonStateSignalChatCall) GetMediaType() ChatMediaType {
	if x != nil {
		return x.MediaType
	}
	return ChatMediaType_UNKNOWN
}

var File_CommonStateSignalChatCall_proto protoreflect.FileDescriptor

var file_CommonStateSignalChatCall_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x53, 0x69, 0x67,
	0x6e, 0x61, 0x6c, 0x43, 0x68, 0x61, 0x74, 0x43, 0x61, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0a, 0x41, 0x63, 0x46, 0x75, 0x6e, 0x44, 0x61, 0x6e, 0x6d, 0x75, 0x1a, 0x13, 0x43,
	0x68, 0x61, 0x74, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xae, 0x01, 0x0a, 0x19, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x43, 0x68, 0x61, 0x74, 0x43, 0x61, 0x6c, 0x6c,
	0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x69, 0x76, 0x65,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x69, 0x76, 0x65, 0x49, 0x64,
	0x12, 0x28, 0x0a, 0x0f, 0x63, 0x61, 0x6c, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x4d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x63, 0x61, 0x6c, 0x6c, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x4d, 0x73, 0x12, 0x37, 0x0a, 0x09, 0x6d, 0x65,
	0x64, 0x69, 0x61, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e,
	0x41, 0x63, 0x46, 0x75, 0x6e, 0x44, 0x61, 0x6e, 0x6d, 0x75, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4d,
	0x65, 0x64, 0x69, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x54,
	0x79, 0x70, 0x65, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6f, 0x72, 0x7a, 0x6f, 0x67, 0x63, 0x2f, 0x61, 0x63, 0x66, 0x75, 0x6e, 0x64, 0x61,
	0x6e, 0x6d, 0x75, 0x2f, 0x61, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_CommonStateSignalChatCall_proto_rawDescOnce sync.Once
	file_CommonStateSignalChatCall_proto_rawDescData = file_CommonStateSignalChatCall_proto_rawDesc
)

func file_CommonStateSignalChatCall_proto_rawDescGZIP() []byte {
	file_CommonStateSignalChatCall_proto_rawDescOnce.Do(func() {
		file_CommonStateSignalChatCall_proto_rawDescData = protoimpl.X.CompressGZIP(file_CommonStateSignalChatCall_proto_rawDescData)
	})
	return file_CommonStateSignalChatCall_proto_rawDescData
}

var file_CommonStateSignalChatCall_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CommonStateSignalChatCall_proto_goTypes = []any{
	(*CommonStateSignalChatCall)(nil), // 0: AcFunDanmu.CommonStateSignalChatCall
	(ChatMediaType)(0),                // 1: AcFunDanmu.ChatMediaType
}
var file_CommonStateSignalChatCall_proto_depIdxs = []int32{
	1, // 0: AcFunDanmu.CommonStateSignalChatCall.mediaType:type_name -> AcFunDanmu.ChatMediaType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_CommonStateSignalChatCall_proto_init() }
func file_CommonStateSignalChatCall_proto_init() {
	if File_CommonStateSignalChatCall_proto != nil {
		return
	}
	file_ChatMediaType_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_CommonStateSignalChatCall_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CommonStateSignalChatCall); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_CommonStateSignalChatCall_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CommonStateSignalChatCall_proto_goTypes,
		DependencyIndexes: file_CommonStateSignalChatCall_proto_depIdxs,
		MessageInfos:      file_CommonStateSignalChatCall_proto_msgTypes,
	}.Build()
	File_CommonStateSignalChatCall_proto = out.File
	file_CommonStateSignalChatCall_proto_rawDesc = nil
	file_CommonStateSignalChatCall_proto_goTypes = nil
	file_CommonStateSignalChatCall_proto_depIdxs = nil
}
