// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: CommonActionSignalUserShareLive.proto

package acproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommonActionSignalUserShareLiveUnknown int32

const (
	CommonActionSignalUserShareLive_e CommonActionSignalUserShareLiveUnknown = 0
	CommonActionSignalUserShareLive_f CommonActionSignalUserShareLiveUnknown = 1
)

// Enum value maps for CommonActionSignalUserShareLiveUnknown.
var (
	CommonActionSignalUserShareLiveUnknown_name = map[int32]string{
		0: "e",
		1: "f",
	}
	CommonActionSignalUserShareLiveUnknown_value = map[string]int32{
		"e": 0,
		"f": 1,
	}
)

func (x CommonActionSignalUserShareLiveUnknown) Enum() *CommonActionSignalUserShareLiveUnknown {
	p := new(CommonActionSignalUserShareLiveUnknown)
	*p = x
	return p
}

func (x CommonActionSignalUserShareLiveUnknown) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommonActionSignalUserShareLiveUnknown) Descriptor() protoreflect.EnumDescriptor {
	return file_CommonActionSignalUserShareLive_proto_enumTypes[0].Descriptor()
}

func (CommonActionSignalUserShareLiveUnknown) Type() protoreflect.EnumType {
	return &file_CommonActionSignalUserShareLive_proto_enumTypes[0]
}

func (x CommonActionSignalUserShareLiveUnknown) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommonActionSignalUserShareLiveUnknown.Descriptor instead.
func (CommonActionSignalUserShareLiveUnknown) EnumDescriptor() ([]byte, []int) {
	return file_CommonActionSignalUserShareLive_proto_rawDescGZIP(), []int{0, 0}
}

type CommonActionSignalUserShareLive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserInfo          *ZtLiveUserInfo `protobuf:"bytes,1,opt,name=userInfo,proto3" json:"userInfo,omitempty"`
	SharePlatformId   int32           `protobuf:"varint,2,opt,name=sharePlatformId,proto3" json:"sharePlatformId,omitempty"`    // platformId
	SharePlatformIcon string          `protobuf:"bytes,3,opt,name=sharePlatformIcon,proto3" json:"sharePlatformIcon,omitempty"` // platformIcon
	SendTimeMs        int64           `protobuf:"varint,4,opt,name=sendTimeMs,proto3" json:"sendTimeMs,omitempty"`
}

func (x *CommonActionSignalUserShareLive) Reset() {
	*x = CommonActionSignalUserShareLive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CommonActionSignalUserShareLive_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonActionSignalUserShareLive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonActionSignalUserShareLive) ProtoMessage() {}

func (x *CommonActionSignalUserShareLive) ProtoReflect() protoreflect.Message {
	mi := &file_CommonActionSignalUserShareLive_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonActionSignalUserShareLive.ProtoReflect.Descriptor instead.
func (*CommonActionSignalUserShareLive) Descriptor() ([]byte, []int) {
	return file_CommonActionSignalUserShareLive_proto_rawDescGZIP(), []int{0}
}

func (x *CommonActionSignalUserShareLive) GetUserInfo() *ZtLiveUserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

func (x *CommonActionSignalUserShareLive) GetSharePlatformId() int32 {
	if x != nil {
		return x.SharePlatformId
	}
	return 0
}

func (x *CommonActionSignalUserShareLive) GetSharePlatformIcon() string {
	if x != nil {
		return x.SharePlatformIcon
	}
	return ""
}

func (x *CommonActionSignalUserShareLive) GetSendTimeMs() int64 {
	if x != nil {
		return x.SendTimeMs
	}
	return 0
}

var File_CommonActionSignalUserShareLive_proto protoreflect.FileDescriptor

var file_CommonActionSignalUserShareLive_proto_rawDesc = []byte{
	0x0a, 0x25, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x53, 0x68, 0x61, 0x72, 0x65, 0x4c, 0x69, 0x76,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x41, 0x63, 0x46, 0x75, 0x6e, 0x44, 0x61,
	0x6e, 0x6d, 0x75, 0x1a, 0x14, 0x5a, 0x74, 0x4c, 0x69, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xea, 0x01, 0x0a, 0x1f, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c,
	0x55, 0x73, 0x65, 0x72, 0x53, 0x68, 0x61, 0x72, 0x65, 0x4c, 0x69, 0x76, 0x65, 0x12, 0x36, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x41, 0x63, 0x46, 0x75, 0x6e, 0x44, 0x61, 0x6e, 0x6d, 0x75, 0x2e, 0x5a, 0x74, 0x4c,
	0x69, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x28, 0x0a, 0x0f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x50, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f,
	0x73, 0x68, 0x61, 0x72, 0x65, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x49, 0x64, 0x12,
	0x2c, 0x0a, 0x11, 0x73, 0x68, 0x61, 0x72, 0x65, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x49, 0x63, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x73, 0x68, 0x61, 0x72,
	0x65, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x49, 0x63, 0x6f, 0x6e, 0x12, 0x1e, 0x0a,
	0x0a, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x4d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x4d, 0x73, 0x22, 0x17, 0x0a,
	0x07, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x12, 0x05, 0x0a, 0x01, 0x65, 0x10, 0x00, 0x12,
	0x05, 0x0a, 0x01, 0x66, 0x10, 0x01, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x72, 0x7a, 0x6f, 0x67, 0x63, 0x2f, 0x61, 0x63, 0x66, 0x75,
	0x6e, 0x64, 0x61, 0x6e, 0x6d, 0x75, 0x2f, 0x61, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_CommonActionSignalUserShareLive_proto_rawDescOnce sync.Once
	file_CommonActionSignalUserShareLive_proto_rawDescData = file_CommonActionSignalUserShareLive_proto_rawDesc
)

func file_CommonActionSignalUserShareLive_proto_rawDescGZIP() []byte {
	file_CommonActionSignalUserShareLive_proto_rawDescOnce.Do(func() {
		file_CommonActionSignalUserShareLive_proto_rawDescData = protoimpl.X.CompressGZIP(file_CommonActionSignalUserShareLive_proto_rawDescData)
	})
	return file_CommonActionSignalUserShareLive_proto_rawDescData
}

var file_CommonActionSignalUserShareLive_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_CommonActionSignalUserShareLive_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CommonActionSignalUserShareLive_proto_goTypes = []any{
	(CommonActionSignalUserShareLiveUnknown)(0), // 0: AcFunDanmu.CommonActionSignalUserShareLive.unknown
	(*CommonActionSignalUserShareLive)(nil),     // 1: AcFunDanmu.CommonActionSignalUserShareLive
	(*ZtLiveUserInfo)(nil),                      // 2: AcFunDanmu.ZtLiveUserInfo
}
var file_CommonActionSignalUserShareLive_proto_depIdxs = []int32{
	2, // 0: AcFunDanmu.CommonActionSignalUserShareLive.userInfo:type_name -> AcFunDanmu.ZtLiveUserInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_CommonActionSignalUserShareLive_proto_init() }
func file_CommonActionSignalUserShareLive_proto_init() {
	if File_CommonActionSignalUserShareLive_proto != nil {
		return
	}
	file_ZtLiveUserInfo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_CommonActionSignalUserShareLive_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CommonActionSignalUserShareLive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_CommonActionSignalUserShareLive_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CommonActionSignalUserShareLive_proto_goTypes,
		DependencyIndexes: file_CommonActionSignalUserShareLive_proto_depIdxs,
		EnumInfos:         file_CommonActionSignalUserShareLive_proto_enumTypes,
		MessageInfos:      file_CommonActionSignalUserShareLive_proto_msgTypes,
	}.Build()
	File_CommonActionSignalUserShareLive_proto = out.File
	file_CommonActionSignalUserShareLive_proto_rawDesc = nil
	file_CommonActionSignalUserShareLive_proto_goTypes = nil
	file_CommonActionSignalUserShareLive_proto_depIdxs = nil
}
