// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: CommonStateSignalShoppingCart.proto

package acproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommonStateSignalShoppingCartUnknown int32

const (
	CommonStateSignalShoppingCart_c CommonStateSignalShoppingCartUnknown = 0
	CommonStateSignalShoppingCart_d CommonStateSignalShoppingCartUnknown = 1
	CommonStateSignalShoppingCart_e CommonStateSignalShoppingCartUnknown = 2
)

// Enum value maps for CommonStateSignalShoppingCartUnknown.
var (
	CommonStateSignalShoppingCartUnknown_name = map[int32]string{
		0: "c",
		1: "d",
		2: "e",
	}
	CommonStateSignalShoppingCartUnknown_value = map[string]int32{
		"c": 0,
		"d": 1,
		"e": 2,
	}
)

func (x CommonStateSignalShoppingCartUnknown) Enum() *CommonStateSignalShoppingCartUnknown {
	p := new(CommonStateSignalShoppingCartUnknown)
	*p = x
	return p
}

func (x CommonStateSignalShoppingCartUnknown) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommonStateSignalShoppingCartUnknown) Descriptor() protoreflect.EnumDescriptor {
	return file_CommonStateSignalShoppingCart_proto_enumTypes[0].Descriptor()
}

func (CommonStateSignalShoppingCartUnknown) Type() protoreflect.EnumType {
	return &file_CommonStateSignalShoppingCart_proto_enumTypes[0]
}

func (x CommonStateSignalShoppingCartUnknown) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommonStateSignalShoppingCartUnknown.Descriptor instead.
func (CommonStateSignalShoppingCartUnknown) EnumDescriptor() ([]byte, []int) {
	return file_CommonStateSignalShoppingCart_proto_rawDescGZIP(), []int{0, 0}
}

type CommonStateSignalShoppingCart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A CommonStateSignalShoppingCartUnknown `protobuf:"varint,1,opt,name=a,proto3,enum=AcFunDanmu.CommonStateSignalShoppingCartUnknown" json:"a,omitempty"`
	B string                               `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
}

func (x *CommonStateSignalShoppingCart) Reset() {
	*x = CommonStateSignalShoppingCart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CommonStateSignalShoppingCart_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonStateSignalShoppingCart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonStateSignalShoppingCart) ProtoMessage() {}

func (x *CommonStateSignalShoppingCart) ProtoReflect() protoreflect.Message {
	mi := &file_CommonStateSignalShoppingCart_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonStateSignalShoppingCart.ProtoReflect.Descriptor instead.
func (*CommonStateSignalShoppingCart) Descriptor() ([]byte, []int) {
	return file_CommonStateSignalShoppingCart_proto_rawDescGZIP(), []int{0}
}

func (x *CommonStateSignalShoppingCart) GetA() CommonStateSignalShoppingCartUnknown {
	if x != nil {
		return x.A
	}
	return CommonStateSignalShoppingCart_c
}

func (x *CommonStateSignalShoppingCart) GetB() string {
	if x != nil {
		return x.B
	}
	return ""
}

var File_CommonStateSignalShoppingCart_proto protoreflect.FileDescriptor

var file_CommonStateSignalShoppingCart_proto_rawDesc = []byte{
	0x0a, 0x23, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x53, 0x69, 0x67,
	0x6e, 0x61, 0x6c, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x41, 0x63, 0x46, 0x75, 0x6e, 0x44, 0x61, 0x6e, 0x6d,
	0x75, 0x22, 0x8e, 0x01, 0x0a, 0x1d, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x43,
	0x61, 0x72, 0x74, 0x12, 0x3f, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x31,
	0x2e, 0x41, 0x63, 0x46, 0x75, 0x6e, 0x44, 0x61, 0x6e, 0x6d, 0x75, 0x2e, 0x43, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x53, 0x68, 0x6f,
	0x70, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x2e, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77,
	0x6e, 0x52, 0x01, 0x61, 0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x01, 0x62, 0x22, 0x1e, 0x0a, 0x07, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x12, 0x05, 0x0a,
	0x01, 0x63, 0x10, 0x00, 0x12, 0x05, 0x0a, 0x01, 0x64, 0x10, 0x01, 0x12, 0x05, 0x0a, 0x01, 0x65,
	0x10, 0x02, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6f, 0x72, 0x7a, 0x6f, 0x67, 0x63, 0x2f, 0x61, 0x63, 0x66, 0x75, 0x6e, 0x64, 0x61, 0x6e,
	0x6d, 0x75, 0x2f, 0x61, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_CommonStateSignalShoppingCart_proto_rawDescOnce sync.Once
	file_CommonStateSignalShoppingCart_proto_rawDescData = file_CommonStateSignalShoppingCart_proto_rawDesc
)

func file_CommonStateSignalShoppingCart_proto_rawDescGZIP() []byte {
	file_CommonStateSignalShoppingCart_proto_rawDescOnce.Do(func() {
		file_CommonStateSignalShoppingCart_proto_rawDescData = protoimpl.X.CompressGZIP(file_CommonStateSignalShoppingCart_proto_rawDescData)
	})
	return file_CommonStateSignalShoppingCart_proto_rawDescData
}

var file_CommonStateSignalShoppingCart_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_CommonStateSignalShoppingCart_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CommonStateSignalShoppingCart_proto_goTypes = []any{
	(CommonStateSignalShoppingCartUnknown)(0), // 0: AcFunDanmu.CommonStateSignalShoppingCart.unknown
	(*CommonStateSignalShoppingCart)(nil),     // 1: AcFunDanmu.CommonStateSignalShoppingCart
}
var file_CommonStateSignalShoppingCart_proto_depIdxs = []int32{
	0, // 0: AcFunDanmu.CommonStateSignalShoppingCart.a:type_name -> AcFunDanmu.CommonStateSignalShoppingCart.unknown
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_CommonStateSignalShoppingCart_proto_init() }
func file_CommonStateSignalShoppingCart_proto_init() {
	if File_CommonStateSignalShoppingCart_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_CommonStateSignalShoppingCart_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CommonStateSignalShoppingCart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_CommonStateSignalShoppingCart_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CommonStateSignalShoppingCart_proto_goTypes,
		DependencyIndexes: file_CommonStateSignalShoppingCart_proto_depIdxs,
		EnumInfos:         file_CommonStateSignalShoppingCart_proto_enumTypes,
		MessageInfos:      file_CommonStateSignalShoppingCart_proto_msgTypes,
	}.Build()
	File_CommonStateSignalShoppingCart_proto = out.File
	file_CommonStateSignalShoppingCart_proto_rawDesc = nil
	file_CommonStateSignalShoppingCart_proto_goTypes = nil
	file_CommonStateSignalShoppingCart_proto_depIdxs = nil
}
