// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: HandshakeRequest.proto

package acproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HandshakeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Unknown1 int32 `protobuf:"varint,1,opt,name=unknown1,proto3" json:"unknown1,omitempty"`
	Unknown2 int32 `protobuf:"varint,2,opt,name=unknown2,proto3" json:"unknown2,omitempty"`
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HandshakeRequest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_HandshakeRequest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_HandshakeRequest_proto_rawDescGZIP(), []int{0}
}

func (x *HandshakeRequest) GetUnknown1() int32 {
	if x != nil {
		return x.Unknown1
	}
	return 0
}

func (x *HandshakeRequest) GetUnknown2() int32 {
	if x != nil {
		return x.Unknown2
	}
	return 0
}

var File_HandshakeRequest_proto protoreflect.FileDescriptor

var file_HandshakeRequest_proto_rawDesc = []byte{
	0x0a, 0x16, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x41, 0x63, 0x46, 0x75, 0x6e, 0x44,
	0x61, 0x6e, 0x6d, 0x75, 0x2e, 0x49, 0x6d, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x22, 0x4a, 0x0a,
	0x10, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x31, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x31, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x32, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x72, 0x7a, 0x6f, 0x67, 0x63, 0x2f, 0x61,
	0x63, 0x66, 0x75, 0x6e, 0x64, 0x61, 0x6e, 0x6d, 0x75, 0x2f, 0x61, 0x63, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_HandshakeRequest_proto_rawDescOnce sync.Once
	file_HandshakeRequest_proto_rawDescData = file_HandshakeRequest_proto_rawDesc
)

func file_HandshakeRequest_proto_rawDescGZIP() []byte {
	file_HandshakeRequest_proto_rawDescOnce.Do(func() {
		file_HandshakeRequest_proto_rawDescData = protoimpl.X.CompressGZIP(file_HandshakeRequest_proto_rawDescData)
	})
	return file_HandshakeRequest_proto_rawDescData
}

var file_HandshakeRequest_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_HandshakeRequest_proto_goTypes = []any{
	(*HandshakeRequest)(nil), // 0: AcFunDanmu.Im.Basic.HandshakeRequest
}
var file_HandshakeRequest_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_HandshakeRequest_proto_init() }
func file_HandshakeRequest_proto_init() {
	if File_HandshakeRequest_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_HandshakeRequest_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*HandshakeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_HandshakeRequest_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_HandshakeRequest_proto_goTypes,
		DependencyIndexes: file_HandshakeRequest_proto_depIdxs,
		MessageInfos:      file_HandshakeRequest_proto_msgTypes,
	}.Build()
	File_HandshakeRequest_proto = out.File
	file_HandshakeRequest_proto_rawDesc = nil
	file_HandshakeRequest_proto_goTypes = nil
	file_HandshakeRequest_proto_depIdxs = nil
}
