// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: PingRequest.proto

package acproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest_PingType int32

const (
	PingRequest_kInvalid       PingRequest_PingType = 0
	PingRequest_kPriorRegister PingRequest_PingType = 1
	PingRequest_kPostRegister  PingRequest_PingType = 2
)

// Enum value maps for PingRequest_PingType.
var (
	PingRequest_PingType_name = map[int32]string{
		0: "kInvalid",
		1: "kPriorRegister",
		2: "kPostRegister",
	}
	PingRequest_PingType_value = map[string]int32{
		"kInvalid":       0,
		"kPriorRegister": 1,
		"kPostRegister":  2,
	}
)

func (x PingRequest_PingType) Enum() *PingRequest_PingType {
	p := new(PingRequest_PingType)
	*p = x
	return p
}

func (x PingRequest_PingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PingRequest_PingType) Descriptor() protoreflect.EnumDescriptor {
	return file_PingRequest_proto_enumTypes[0].Descriptor()
}

func (PingRequest_PingType) Type() protoreflect.EnumType {
	return &file_PingRequest_proto_enumTypes[0]
}

func (x PingRequest_PingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PingRequest_PingType.Descriptor instead.
func (PingRequest_PingType) EnumDescriptor() ([]byte, []int) {
	return file_PingRequest_proto_rawDescGZIP(), []int{0, 0}
}

type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PingType  PingRequest_PingType `protobuf:"varint,1,opt,name=pingType,proto3,enum=AcFunDanmu.Im.Basic.PingRequest_PingType" json:"pingType,omitempty"`
	PingRound uint32               `protobuf:"varint,2,opt,name=pingRound,proto3" json:"pingRound,omitempty"`
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PingRequest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PingRequest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_PingRequest_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetPingType() PingRequest_PingType {
	if x != nil {
		return x.PingType
	}
	return PingRequest_kInvalid
}

func (x *PingRequest) GetPingRound() uint32 {
	if x != nil {
		return x.PingRound
	}
	return 0
}

var File_PingRequest_proto protoreflect.FileDescriptor

var file_PingRequest_proto_rawDesc = []byte{
	0x0a, 0x11, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x13, 0x41, 0x63, 0x46, 0x75, 0x6e, 0x44, 0x61, 0x6e, 0x6d, 0x75, 0x2e,
	0x49, 0x6d, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x22, 0xb3, 0x01, 0x0a, 0x0b, 0x50, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x45, 0x0a, 0x08, 0x70, 0x69, 0x6e, 0x67,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x41, 0x63, 0x46,
	0x75, 0x6e, 0x44, 0x61, 0x6e, 0x6d, 0x75, 0x2e, 0x49, 0x6d, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63,
	0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x69, 0x6e,
	0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x70, 0x69, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x70, 0x69, 0x6e, 0x67, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x70, 0x69, 0x6e, 0x67, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x22, 0x3f, 0x0a,
	0x08, 0x50, 0x69, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x6b, 0x49, 0x6e,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x6b, 0x50, 0x72, 0x69, 0x6f,
	0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x6b,
	0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x10, 0x02, 0x42, 0x26,
	0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x72, 0x7a,
	0x6f, 0x67, 0x63, 0x2f, 0x61, 0x63, 0x66, 0x75, 0x6e, 0x64, 0x61, 0x6e, 0x6d, 0x75, 0x2f, 0x61,
	0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_PingRequest_proto_rawDescOnce sync.Once
	file_PingRequest_proto_rawDescData = file_PingRequest_proto_rawDesc
)

func file_PingRequest_proto_rawDescGZIP() []byte {
	file_PingRequest_proto_rawDescOnce.Do(func() {
		file_PingRequest_proto_rawDescData = protoimpl.X.CompressGZIP(file_PingRequest_proto_rawDescData)
	})
	return file_PingRequest_proto_rawDescData
}

var file_PingRequest_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_PingRequest_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PingRequest_proto_goTypes = []any{
	(PingRequest_PingType)(0), // 0: AcFunDanmu.Im.Basic.PingRequest.PingType
	(*PingRequest)(nil),       // 1: AcFunDanmu.Im.Basic.PingRequest
}
var file_PingRequest_proto_depIdxs = []int32{
	0, // 0: AcFunDanmu.Im.Basic.PingRequest.pingType:type_name -> AcFunDanmu.Im.Basic.PingRequest.PingType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_PingRequest_proto_init() }
func file_PingRequest_proto_init() {
	if File_PingRequest_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_PingRequest_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_PingRequest_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PingRequest_proto_goTypes,
		DependencyIndexes: file_PingRequest_proto_depIdxs,
		EnumInfos:         file_PingRequest_proto_enumTypes,
		MessageInfos:      file_PingRequest_proto_msgTypes,
	}.Build()
	File_PingRequest_proto = out.File
	file_PingRequest_proto_rawDesc = nil
	file_PingRequest_proto_goTypes = nil
	file_PingRequest_proto_depIdxs = nil
}
