// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: TopBannerNotice.proto

package acproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TopBannerNotice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A string           `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	B string           `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
	C string           `protobuf:"bytes,3,opt,name=c,proto3" json:"c,omitempty"`
	D *BackgroundStyle `protobuf:"bytes,4,opt,name=d,proto3" json:"d,omitempty"`
	E int32            `protobuf:"varint,5,opt,name=e,proto3" json:"e,omitempty"`
	F *Button          `protobuf:"bytes,6,opt,name=f,proto3" json:"f,omitempty"`
	G []*ImageCdnNode  `protobuf:"bytes,7,rep,name=g,proto3" json:"g,omitempty"`
	H int64            `protobuf:"varint,8,opt,name=h,proto3" json:"h,omitempty"`
}

func (x *TopBannerNotice) Reset() {
	*x = TopBannerNotice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TopBannerNotice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopBannerNotice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopBannerNotice) ProtoMessage() {}

func (x *TopBannerNotice) ProtoReflect() protoreflect.Message {
	mi := &file_TopBannerNotice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopBannerNotice.ProtoReflect.Descriptor instead.
func (*TopBannerNotice) Descriptor() ([]byte, []int) {
	return file_TopBannerNotice_proto_rawDescGZIP(), []int{0}
}

func (x *TopBannerNotice) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

func (x *TopBannerNotice) GetB() string {
	if x != nil {
		return x.B
	}
	return ""
}

func (x *TopBannerNotice) GetC() string {
	if x != nil {
		return x.C
	}
	return ""
}

func (x *TopBannerNotice) GetD() *BackgroundStyle {
	if x != nil {
		return x.D
	}
	return nil
}

func (x *TopBannerNotice) GetE() int32 {
	if x != nil {
		return x.E
	}
	return 0
}

func (x *TopBannerNotice) GetF() *Button {
	if x != nil {
		return x.F
	}
	return nil
}

func (x *TopBannerNotice) GetG() []*ImageCdnNode {
	if x != nil {
		return x.G
	}
	return nil
}

func (x *TopBannerNotice) GetH() int64 {
	if x != nil {
		return x.H
	}
	return 0
}

var File_TopBannerNotice_proto protoreflect.FileDescriptor

var file_TopBannerNotice_proto_rawDesc = []byte{
	0x0a, 0x15, 0x54, 0x6f, 0x70, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x41, 0x63, 0x46, 0x75, 0x6e, 0x44, 0x61,
	0x6e, 0x6d, 0x75, 0x1a, 0x15, 0x42, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x53,
	0x74, 0x79, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x42, 0x75, 0x74, 0x74,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x43,
	0x64, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xcc, 0x01, 0x0a,
	0x0f, 0x54, 0x6f, 0x70, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65,
	0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x61, 0x12, 0x0c,
	0x0a, 0x01, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x62, 0x12, 0x0c, 0x0a, 0x01,
	0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x63, 0x12, 0x29, 0x0a, 0x01, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x41, 0x63, 0x46, 0x75, 0x6e, 0x44, 0x61, 0x6e,
	0x6d, 0x75, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x53, 0x74, 0x79,
	0x6c, 0x65, 0x52, 0x01, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x01, 0x65, 0x12, 0x20, 0x0a, 0x01, 0x66, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x41, 0x63, 0x46, 0x75, 0x6e, 0x44, 0x61, 0x6e, 0x6d, 0x75, 0x2e, 0x42, 0x75, 0x74, 0x74,
	0x6f, 0x6e, 0x52, 0x01, 0x66, 0x12, 0x26, 0x0a, 0x01, 0x67, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x41, 0x63, 0x46, 0x75, 0x6e, 0x44, 0x61, 0x6e, 0x6d, 0x75, 0x2e, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x43, 0x64, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x01, 0x67, 0x12, 0x0c, 0x0a,
	0x01, 0x68, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x68, 0x42, 0x26, 0x5a, 0x24, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x72, 0x7a, 0x6f, 0x67, 0x63,
	0x2f, 0x61, 0x63, 0x66, 0x75, 0x6e, 0x64, 0x61, 0x6e, 0x6d, 0x75, 0x2f, 0x61, 0x63, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_TopBannerNotice_proto_rawDescOnce sync.Once
	file_TopBannerNotice_proto_rawDescData = file_TopBannerNotice_proto_rawDesc
)

func file_TopBannerNotice_proto_rawDescGZIP() []byte {
	file_TopBannerNotice_proto_rawDescOnce.Do(func() {
		file_TopBannerNotice_proto_rawDescData = protoimpl.X.CompressGZIP(file_TopBannerNotice_proto_rawDescData)
	})
	return file_TopBannerNotice_proto_rawDescData
}

var file_TopBannerNotice_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_TopBannerNotice_proto_goTypes = []any{
	(*TopBannerNotice)(nil), // 0: AcFunDanmu.TopBannerNotice
	(*BackgroundStyle)(nil), // 1: AcFunDanmu.BackgroundStyle
	(*Button)(nil),          // 2: AcFunDanmu.Button
	(*ImageCdnNode)(nil),    // 3: AcFunDanmu.ImageCdnNode
}
var file_TopBannerNotice_proto_depIdxs = []int32{
	1, // 0: AcFunDanmu.TopBannerNotice.d:type_name -> AcFunDanmu.BackgroundStyle
	2, // 1: AcFunDanmu.TopBannerNotice.f:type_name -> AcFunDanmu.Button
	3, // 2: AcFunDanmu.TopBannerNotice.g:type_name -> AcFunDanmu.ImageCdnNode
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_TopBannerNotice_proto_init() }
func file_TopBannerNotice_proto_init() {
	if File_TopBannerNotice_proto != nil {
		return
	}
	file_BackgroundStyle_proto_init()
	file_Button_proto_init()
	file_ImageCdnNode_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_TopBannerNotice_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*TopBannerNotice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_TopBannerNotice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TopBannerNotice_proto_goTypes,
		DependencyIndexes: file_TopBannerNotice_proto_depIdxs,
		MessageInfos:      file_TopBannerNotice_proto_msgTypes,
	}.Build()
	File_TopBannerNotice_proto = out.File
	file_TopBannerNotice_proto_rawDesc = nil
	file_TopBannerNotice_proto_goTypes = nil
	file_TopBannerNotice_proto_depIdxs = nil
}
