// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: WidgetDisplayStyle.proto

package acproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WidgetDisplayStyle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A bool `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B bool `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
}

func (x *WidgetDisplayStyle) Reset() {
	*x = WidgetDisplayStyle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_WidgetDisplayStyle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WidgetDisplayStyle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetDisplayStyle) ProtoMessage() {}

func (x *WidgetDisplayStyle) ProtoReflect() protoreflect.Message {
	mi := &file_WidgetDisplayStyle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetDisplayStyle.ProtoReflect.Descriptor instead.
func (*WidgetDisplayStyle) Descriptor() ([]byte, []int) {
	return file_WidgetDisplayStyle_proto_rawDescGZIP(), []int{0}
}

func (x *WidgetDisplayStyle) GetA() bool {
	if x != nil {
		return x.A
	}
	return false
}

func (x *WidgetDisplayStyle) GetB() bool {
	if x != nil {
		return x.B
	}
	return false
}

var File_WidgetDisplayStyle_proto protoreflect.FileDescriptor

var file_WidgetDisplayStyle_proto_rawDesc = []byte{
	0x0a, 0x18, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x53,
	0x74, 0x79, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x41, 0x63, 0x46, 0x75,
	0x6e, 0x44, 0x61, 0x6e, 0x6d, 0x75, 0x22, 0x30, 0x0a, 0x12, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74,
	0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x12, 0x0c, 0x0a, 0x01,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x01, 0x61, 0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x01, 0x62, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x72, 0x7a, 0x6f, 0x67, 0x63, 0x2f, 0x61, 0x63,
	0x66, 0x75, 0x6e, 0x64, 0x61, 0x6e, 0x6d, 0x75, 0x2f, 0x61, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_WidgetDisplayStyle_proto_rawDescOnce sync.Once
	file_WidgetDisplayStyle_proto_rawDescData = file_WidgetDisplayStyle_proto_rawDesc
)

func file_WidgetDisplayStyle_proto_rawDescGZIP() []byte {
	file_WidgetDisplayStyle_proto_rawDescOnce.Do(func() {
		file_WidgetDisplayStyle_proto_rawDescData = protoimpl.X.CompressGZIP(file_WidgetDisplayStyle_proto_rawDescData)
	})
	return file_WidgetDisplayStyle_proto_rawDescData
}

var file_WidgetDisplayStyle_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_WidgetDisplayStyle_proto_goTypes = []any{
	(*WidgetDisplayStyle)(nil), // 0: AcFunDanmu.WidgetDisplayStyle
}
var file_WidgetDisplayStyle_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_WidgetDisplayStyle_proto_init() }
func file_WidgetDisplayStyle_proto_init() {
	if File_WidgetDisplayStyle_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_WidgetDisplayStyle_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*WidgetDisplayStyle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_WidgetDisplayStyle_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_WidgetDisplayStyle_proto_goTypes,
		DependencyIndexes: file_WidgetDisplayStyle_proto_depIdxs,
		MessageInfos:      file_WidgetDisplayStyle_proto_msgTypes,
	}.Build()
	File_WidgetDisplayStyle_proto = out.File
	file_WidgetDisplayStyle_proto_rawDesc = nil
	file_WidgetDisplayStyle_proto_goTypes = nil
	file_WidgetDisplayStyle_proto_depIdxs = nil
}
