// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: ZtCommonInfo.proto

package acproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ZtCommonInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kpn         string `protobuf:"bytes,1,opt,name=kpn,proto3" json:"kpn,omitempty"`
	Kpf         string `protobuf:"bytes,2,opt,name=kpf,proto3" json:"kpf,omitempty"`
	SubBiz      string `protobuf:"bytes,3,opt,name=subBiz,proto3" json:"subBiz,omitempty"`
	Uid         int64  `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	Did         string `protobuf:"bytes,5,opt,name=did,proto3" json:"did,omitempty"`
	ClientIp    int64  `protobuf:"varint,6,opt,name=clientIp,proto3" json:"clientIp,omitempty"`
	AppVer      string `protobuf:"bytes,7,opt,name=appVer,proto3" json:"appVer,omitempty"`
	Ver         string `protobuf:"bytes,8,opt,name=ver,proto3" json:"ver,omitempty"`
	Lat         string `protobuf:"bytes,9,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon         string `protobuf:"bytes,10,opt,name=lon,proto3" json:"lon,omitempty"`
	Mod         string `protobuf:"bytes,11,opt,name=mod,proto3" json:"mod,omitempty"`
	Net         string `protobuf:"bytes,12,opt,name=net,proto3" json:"net,omitempty"`
	Sys         string `protobuf:"bytes,13,opt,name=sys,proto3" json:"sys,omitempty"`
	C           string `protobuf:"bytes,14,opt,name=c,proto3" json:"c,omitempty"`
	Language    string `protobuf:"bytes,15,opt,name=language,proto3" json:"language,omitempty"`
	CountryCode string `protobuf:"bytes,16,opt,name=countryCode,proto3" json:"countryCode,omitempty"`
}

func (x *ZtCommonInfo) Reset() {
	*x = ZtCommonInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ZtCommonInfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZtCommonInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZtCommonInfo) ProtoMessage() {}

func (x *ZtCommonInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ZtCommonInfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZtCommonInfo.ProtoReflect.Descriptor instead.
func (*ZtCommonInfo) Descriptor() ([]byte, []int) {
	return file_ZtCommonInfo_proto_rawDescGZIP(), []int{0}
}

func (x *ZtCommonInfo) GetKpn() string {
	if x != nil {
		return x.Kpn
	}
	return ""
}

func (x *ZtCommonInfo) GetKpf() string {
	if x != nil {
		return x.Kpf
	}
	return ""
}

func (x *ZtCommonInfo) GetSubBiz() string {
	if x != nil {
		return x.SubBiz
	}
	return ""
}

func (x *ZtCommonInfo) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ZtCommonInfo) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *ZtCommonInfo) GetClientIp() int64 {
	if x != nil {
		return x.ClientIp
	}
	return 0
}

func (x *ZtCommonInfo) GetAppVer() string {
	if x != nil {
		return x.AppVer
	}
	return ""
}

func (x *ZtCommonInfo) GetVer() string {
	if x != nil {
		return x.Ver
	}
	return ""
}

func (x *ZtCommonInfo) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

func (x *ZtCommonInfo) GetLon() string {
	if x != nil {
		return x.Lon
	}
	return ""
}

func (x *ZtCommonInfo) GetMod() string {
	if x != nil {
		return x.Mod
	}
	return ""
}

func (x *ZtCommonInfo) GetNet() string {
	if x != nil {
		return x.Net
	}
	return ""
}

func (x *ZtCommonInfo) GetSys() string {
	if x != nil {
		return x.Sys
	}
	return ""
}

func (x *ZtCommonInfo) GetC() string {
	if x != nil {
		return x.C
	}
	return ""
}

func (x *ZtCommonInfo) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ZtCommonInfo) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

var File_ZtCommonInfo_proto protoreflect.FileDescriptor

var file_ZtCommonInfo_proto_rawDesc = []byte{
	0x0a, 0x12, 0x5a, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x41, 0x63, 0x46, 0x75, 0x6e, 0x44, 0x61, 0x6e, 0x6d, 0x75,
	0x2e, 0x49, 0x6d, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x22, 0xda, 0x02, 0x0a, 0x0c, 0x5a, 0x74,
	0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x70,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x70, 0x6e, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x70, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x70, 0x66, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x75, 0x62, 0x42, 0x69, 0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x75, 0x62, 0x42, 0x69, 0x7a, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x49, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x49, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x56, 0x65, 0x72,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x70, 0x56, 0x65, 0x72, 0x12, 0x10,
	0x0a, 0x03, 0x76, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x76, 0x65, 0x72,
	0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c,
	0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6c, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x6f, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x6f, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x65, 0x74, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x79, 0x73, 0x18,
	0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x79, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x63, 0x18,
	0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67,
	0x75, 0x61, 0x67, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67,
	0x75, 0x61, 0x67, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x72, 0x7a, 0x6f, 0x67, 0x63, 0x2f, 0x61, 0x63, 0x66, 0x75,
	0x6e, 0x64, 0x61, 0x6e, 0x6d, 0x75, 0x2f, 0x61, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ZtCommonInfo_proto_rawDescOnce sync.Once
	file_ZtCommonInfo_proto_rawDescData = file_ZtCommonInfo_proto_rawDesc
)

func file_ZtCommonInfo_proto_rawDescGZIP() []byte {
	file_ZtCommonInfo_proto_rawDescOnce.Do(func() {
		file_ZtCommonInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_ZtCommonInfo_proto_rawDescData)
	})
	return file_ZtCommonInfo_proto_rawDescData
}

var file_ZtCommonInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ZtCommonInfo_proto_goTypes = []any{
	(*ZtCommonInfo)(nil), // 0: AcFunDanmu.Im.Basic.ZtCommonInfo
}
var file_ZtCommonInfo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ZtCommonInfo_proto_init() }
func file_ZtCommonInfo_proto_init() {
	if File_ZtCommonInfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ZtCommonInfo_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ZtCommonInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ZtCommonInfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ZtCommonInfo_proto_goTypes,
		DependencyIndexes: file_ZtCommonInfo_proto_depIdxs,
		MessageInfos:      file_ZtCommonInfo_proto_msgTypes,
	}.Build()
	File_ZtCommonInfo_proto = out.File
	file_ZtCommonInfo_proto_rawDesc = nil
	file_ZtCommonInfo_proto_goTypes = nil
	file_ZtCommonInfo_proto_depIdxs = nil
}
