// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.16.0
// source: ZtLiveChatProto.proto

package acproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ZtLiveChatProto int32

const (
	ZtLiveChatProto_a ZtLiveChatProto = 0
	ZtLiveChatProto_b ZtLiveChatProto = 1
	ZtLiveChatProto_c ZtLiveChatProto = 2
)

// Enum value maps for ZtLiveChatProto.
var (
	ZtLiveChatProto_name = map[int32]string{
		0: "a",
		1: "b",
		2: "c",
	}
	ZtLiveChatProto_value = map[string]int32{
		"a": 0,
		"b": 1,
		"c": 2,
	}
)

func (x ZtLiveChatProto) Enum() *ZtLiveChatProto {
	p := new(ZtLiveChatProto)
	*p = x
	return p
}

func (x ZtLiveChatProto) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ZtLiveChatProto) Descriptor() protoreflect.EnumDescriptor {
	return file_ZtLiveChatProto_proto_enumTypes[0].Descriptor()
}

func (ZtLiveChatProto) Type() protoreflect.EnumType {
	return &file_ZtLiveChatProto_proto_enumTypes[0]
}

func (x ZtLiveChatProto) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ZtLiveChatProto.Descriptor instead.
func (ZtLiveChatProto) EnumDescriptor() ([]byte, []int) {
	return file_ZtLiveChatProto_proto_rawDescGZIP(), []int{0}
}

var File_ZtLiveChatProto_proto protoreflect.FileDescriptor

var file_ZtLiveChatProto_proto_rawDesc = []byte{
	0x0a, 0x15, 0x5a, 0x74, 0x4c, 0x69, 0x76, 0x65, 0x43, 0x68, 0x61, 0x74, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x41, 0x63, 0x46, 0x75, 0x6e, 0x44, 0x61,
	0x6e, 0x6d, 0x75, 0x2a, 0x26, 0x0a, 0x0f, 0x5a, 0x74, 0x4c, 0x69, 0x76, 0x65, 0x43, 0x68, 0x61,
	0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x0a, 0x01, 0x61, 0x10, 0x00, 0x12, 0x05, 0x0a,
	0x01, 0x62, 0x10, 0x01, 0x12, 0x05, 0x0a, 0x01, 0x63, 0x10, 0x02, 0x42, 0x26, 0x5a, 0x24, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x72, 0x7a, 0x6f, 0x67, 0x63,
	0x2f, 0x61, 0x63, 0x66, 0x75, 0x6e, 0x64, 0x61, 0x6e, 0x6d, 0x75, 0x2f, 0x61, 0x63, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ZtLiveChatProto_proto_rawDescOnce sync.Once
	file_ZtLiveChatProto_proto_rawDescData = file_ZtLiveChatProto_proto_rawDesc
)

func file_ZtLiveChatProto_proto_rawDescGZIP() []byte {
	file_ZtLiveChatProto_proto_rawDescOnce.Do(func() {
		file_ZtLiveChatProto_proto_rawDescData = protoimpl.X.CompressGZIP(file_ZtLiveChatProto_proto_rawDescData)
	})
	return file_ZtLiveChatProto_proto_rawDescData
}

var file_ZtLiveChatProto_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ZtLiveChatProto_proto_goTypes = []interface{}{
	(ZtLiveChatProto)(0), // 0: AcFunDanmu.ZtLiveChatProto
}
var file_ZtLiveChatProto_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ZtLiveChatProto_proto_init() }
func file_ZtLiveChatProto_proto_init() {
	if File_ZtLiveChatProto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ZtLiveChatProto_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ZtLiveChatProto_proto_goTypes,
		DependencyIndexes: file_ZtLiveChatProto_proto_depIdxs,
		EnumInfos:         file_ZtLiveChatProto_proto_enumTypes,
	}.Build()
	File_ZtLiveChatProto_proto = out.File
	file_ZtLiveChatProto_proto_rawDesc = nil
	file_ZtLiveChatProto_proto_goTypes = nil
	file_ZtLiveChatProto_proto_depIdxs = nil
}
