// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: ZtLiveCsHeartbeat.proto

package acproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ZtLiveCsHeartbeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientTimestampMs int64 `protobuf:"varint,1,opt,name=clientTimestampMs,proto3" json:"clientTimestampMs,omitempty"`
	Sequence          int64 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
}

func (x *ZtLiveCsHeartbeat) Reset() {
	*x = ZtLiveCsHeartbeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ZtLiveCsHeartbeat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZtLiveCsHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZtLiveCsHeartbeat) ProtoMessage() {}

func (x *ZtLiveCsHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_ZtLiveCsHeartbeat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZtLiveCsHeartbeat.ProtoReflect.Descriptor instead.
func (*ZtLiveCsHeartbeat) Descriptor() ([]byte, []int) {
	return file_ZtLiveCsHeartbeat_proto_rawDescGZIP(), []int{0}
}

func (x *ZtLiveCsHeartbeat) GetClientTimestampMs() int64 {
	if x != nil {
		return x.ClientTimestampMs
	}
	return 0
}

func (x *ZtLiveCsHeartbeat) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type ZtLiveCsHeartbeatAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerTimestampMs int64 `protobuf:"varint,1,opt,name=serverTimestampMs,proto3" json:"serverTimestampMs,omitempty"`
	ClientTimestampMs int64 `protobuf:"varint,2,opt,name=clientTimestampMs,proto3" json:"clientTimestampMs,omitempty"`
	ClientSequence    int64 `protobuf:"varint,3,opt,name=clientSequence,proto3" json:"clientSequence,omitempty"`
}

func (x *ZtLiveCsHeartbeatAck) Reset() {
	*x = ZtLiveCsHeartbeatAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ZtLiveCsHeartbeat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZtLiveCsHeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZtLiveCsHeartbeatAck) ProtoMessage() {}

func (x *ZtLiveCsHeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_ZtLiveCsHeartbeat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZtLiveCsHeartbeatAck.ProtoReflect.Descriptor instead.
func (*ZtLiveCsHeartbeatAck) Descriptor() ([]byte, []int) {
	return file_ZtLiveCsHeartbeat_proto_rawDescGZIP(), []int{1}
}

func (x *ZtLiveCsHeartbeatAck) GetServerTimestampMs() int64 {
	if x != nil {
		return x.ServerTimestampMs
	}
	return 0
}

func (x *ZtLiveCsHeartbeatAck) GetClientTimestampMs() int64 {
	if x != nil {
		return x.ClientTimestampMs
	}
	return 0
}

func (x *ZtLiveCsHeartbeatAck) GetClientSequence() int64 {
	if x != nil {
		return x.ClientSequence
	}
	return 0
}

var File_ZtLiveCsHeartbeat_proto protoreflect.FileDescriptor

var file_ZtLiveCsHeartbeat_proto_rawDesc = []byte{
	0x0a, 0x17, 0x5a, 0x74, 0x4c, 0x69, 0x76, 0x65, 0x43, 0x73, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62,
	0x65, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x41, 0x63, 0x46, 0x75, 0x6e,
	0x44, 0x61, 0x6e, 0x6d, 0x75, 0x22, 0x5d, 0x0a, 0x11, 0x5a, 0x74, 0x4c, 0x69, 0x76, 0x65, 0x43,
	0x73, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x2c, 0x0a, 0x11, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x4d, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x4d, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x71, 0x75,
	0x65, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x71, 0x75,
	0x65, 0x6e, 0x63, 0x65, 0x22, 0x9a, 0x01, 0x0a, 0x14, 0x5a, 0x74, 0x4c, 0x69, 0x76, 0x65, 0x43,
	0x73, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x41, 0x63, 0x6b, 0x12, 0x2c, 0x0a,
	0x11, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x4d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x4d, 0x73, 0x12, 0x2c, 0x0a, 0x11, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x4d, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x4d, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63,
	0x65, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6f, 0x72, 0x7a, 0x6f, 0x67, 0x63, 0x2f, 0x61, 0x63, 0x66, 0x75, 0x6e, 0x64, 0x61, 0x6e, 0x6d,
	0x75, 0x2f, 0x61, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_ZtLiveCsHeartbeat_proto_rawDescOnce sync.Once
	file_ZtLiveCsHeartbeat_proto_rawDescData = file_ZtLiveCsHeartbeat_proto_rawDesc
)

func file_ZtLiveCsHeartbeat_proto_rawDescGZIP() []byte {
	file_ZtLiveCsHeartbeat_proto_rawDescOnce.Do(func() {
		file_ZtLiveCsHeartbeat_proto_rawDescData = protoimpl.X.CompressGZIP(file_ZtLiveCsHeartbeat_proto_rawDescData)
	})
	return file_ZtLiveCsHeartbeat_proto_rawDescData
}

var file_ZtLiveCsHeartbeat_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ZtLiveCsHeartbeat_proto_goTypes = []any{
	(*ZtLiveCsHeartbeat)(nil),    // 0: AcFunDanmu.ZtLiveCsHeartbeat
	(*ZtLiveCsHeartbeatAck)(nil), // 1: AcFunDanmu.ZtLiveCsHeartbeatAck
}
var file_ZtLiveCsHeartbeat_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ZtLiveCsHeartbeat_proto_init() }
func file_ZtLiveCsHeartbeat_proto_init() {
	if File_ZtLiveCsHeartbeat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ZtLiveCsHeartbeat_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ZtLiveCsHeartbeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ZtLiveCsHeartbeat_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ZtLiveCsHeartbeatAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ZtLiveCsHeartbeat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ZtLiveCsHeartbeat_proto_goTypes,
		DependencyIndexes: file_ZtLiveCsHeartbeat_proto_depIdxs,
		MessageInfos:      file_ZtLiveCsHeartbeat_proto_msgTypes,
	}.Build()
	File_ZtLiveCsHeartbeat_proto = out.File
	file_ZtLiveCsHeartbeat_proto_rawDesc = nil
	file_ZtLiveCsHeartbeat_proto_goTypes = nil
	file_ZtLiveCsHeartbeat_proto_depIdxs = nil
}
